from __future__ import annotations

from tfstride.resource_metadata import (
    BoolMetadataField,
    DictListMetadataField,
    DictMetadataField,
    OptionalStringMetadataField,
    StringListMetadataField,
)


class GcpResourceMetadata:
    """GCP-owned metadata fields preserved by the provider normalizers."""

    NAME = OptionalStringMetadataField("name")
    SELF_LINK = OptionalStringMetadataField("self_link")
    PROJECT = OptionalStringMetadataField("project")
    REGION = OptionalStringMetadataField("region")
    ZONE = OptionalStringMetadataField("zone")
    NETWORK = OptionalStringMetadataField("network")
    SUBNETWORK = OptionalStringMetadataField("subnetwork")
    CIDR_RANGE = OptionalStringMetadataField("cidr_range")
    MACHINE_TYPE = OptionalStringMetadataField("machine_type")
    DATABASE_VERSION = OptionalStringMetadataField("database_version")
    CLOUD_SQL_PRIVATE_NETWORK = OptionalStringMetadataField("cloud_sql_private_network")
    CLOUD_SQL_SSL_MODE = OptionalStringMetadataField("cloud_sql_ssl_mode")
    IAM_ROLE = OptionalStringMetadataField("iam_role")
    IAM_MEMBER = OptionalStringMetadataField("iam_member")
    CUSTOM_ROLE_ID = OptionalStringMetadataField("custom_role_id")
    CUSTOM_ROLE_STAGE = OptionalStringMetadataField("custom_role_stage")
    ORGANIZATION_ID = OptionalStringMetadataField("organization_id")
    BUCKET_NAME = OptionalStringMetadataField("bucket")
    SERVICE_ACCOUNT_ACCOUNT_ID = OptionalStringMetadataField("service_account_account_id")
    SERVICE_ACCOUNT_EMAIL = OptionalStringMetadataField("service_account_email")
    SERVICE_ACCOUNT_MEMBER = OptionalStringMetadataField("service_account_member")
    SERVICE_ACCOUNT_REFERENCE = OptionalStringMetadataField("service_account_reference")
    CLOUD_RUN_SERVICE_REFERENCE = OptionalStringMetadataField("cloud_run_service_reference")
    CLOUD_FUNCTION_REFERENCE = OptionalStringMetadataField("cloud_function_reference")
    SERVERLESS_INGRESS = OptionalStringMetadataField("serverless_ingress")
    SERVICE_ACCOUNT_UNIQUE_ID = OptionalStringMetadataField("service_account_unique_id")
    SERVICE_ACCOUNT_KEY_ALGORITHM = OptionalStringMetadataField("service_account_key_algorithm")
    SERVICE_ACCOUNT_PUBLIC_KEY_TYPE = OptionalStringMetadataField("service_account_public_key_type")
    SECRET_ID = OptionalStringMetadataField("secret_id")
    SECRET_REFERENCE = OptionalStringMetadataField("secret_reference")
    KMS_CRYPTO_KEY_REFERENCE = OptionalStringMetadataField("kms_crypto_key_reference")
    KMS_KEY_RING = OptionalStringMetadataField("kms_key_ring")
    KMS_PURPOSE = OptionalStringMetadataField("kms_purpose")
    KMS_ROTATION_PERIOD = OptionalStringMetadataField("kms_rotation_period")
    PUBLIC_ACCESS_PREVENTION = OptionalStringMetadataField("public_access_prevention")
    GCS_DEFAULT_KMS_KEY_NAME = OptionalStringMetadataField("gcs_default_kms_key_name")
    ROUTE_DEST_RANGE = OptionalStringMetadataField("route_dest_range")
    ROUTE_NEXT_HOP_GATEWAY = OptionalStringMetadataField("route_next_hop_gateway")
    ROUTE_NEXT_HOP_INSTANCE = OptionalStringMetadataField("route_next_hop_instance")
    ROUTE_NEXT_HOP_IP = OptionalStringMetadataField("route_next_hop_ip")
    ROUTE_NEXT_HOP_ILB = OptionalStringMetadataField("route_next_hop_ilb")
    ROUTE_NEXT_HOP_VPN_TUNNEL = OptionalStringMetadataField("route_next_hop_vpn_tunnel")
    ROUTER_REFERENCE = OptionalStringMetadataField("router_reference")
    FORWARDING_RULE_IP_ADDRESS = OptionalStringMetadataField("forwarding_rule_ip_address")
    FORWARDING_RULE_LOAD_BALANCING_SCHEME = OptionalStringMetadataField("forwarding_rule_load_balancing_scheme")
    FORWARDING_RULE_TARGET = OptionalStringMetadataField("forwarding_rule_target")
    FORWARDING_RULE_BACKEND_SERVICE = OptionalStringMetadataField("forwarding_rule_backend_service")

    AUTO_CREATE_SUBNETWORKS = BoolMetadataField("auto_create_subnetworks")
    PRIVATE_IP_GOOGLE_ACCESS = BoolMetadataField("private_ip_google_access")
    UNIFORM_BUCKET_LEVEL_ACCESS = BoolMetadataField("uniform_bucket_level_access")
    GCS_VERSIONING_ENABLED = BoolMetadataField("gcs_versioning_enabled")
    SERVICE_ACCOUNT_DISABLED = BoolMetadataField("service_account_disabled")
    OS_LOGIN_ENABLED = BoolMetadataField("os_login_enabled")
    CLOUD_SQL_IPV4_ENABLED = BoolMetadataField("cloud_sql_ipv4_enabled")
    CLOUD_SQL_BACKUP_ENABLED = BoolMetadataField("cloud_sql_backup_enabled")
    CLOUD_SQL_POINT_IN_TIME_RECOVERY_ENABLED = BoolMetadataField("cloud_sql_point_in_time_recovery_enabled")
    CLOUD_SQL_REQUIRE_SSL = BoolMetadataField("cloud_sql_require_ssl")
    DELETION_PROTECTION = BoolMetadataField("deletion_protection")

    NETWORK_TAGS = StringListMetadataField("network_tags")
    IAM_MEMBERS = StringListMetadataField("iam_members")
    CUSTOM_ROLE_PERMISSIONS = StringListMetadataField("custom_role_permissions")
    RESOURCE_POLICY_SOURCE_ADDRESSES = StringListMetadataField("gcp_resource_policy_source_addresses")
    INTERNET_INGRESS_FIREWALLS = StringListMetadataField("internet_ingress_firewalls")
    FIREWALL_SOURCE_RANGES = StringListMetadataField("source_ranges")
    FIREWALL_DESTINATION_RANGES = StringListMetadataField("destination_ranges")
    FIREWALL_TARGET_TAGS = StringListMetadataField("target_tags")
    FIREWALL_SOURCE_TAGS = StringListMetadataField("source_tags")
    FIREWALL_TARGET_SERVICE_ACCOUNTS = StringListMetadataField("target_service_accounts")
    FIREWALL_SOURCE_SERVICE_ACCOUNTS = StringListMetadataField("source_service_accounts")
    ROUTE_TAGS = StringListMetadataField("route_tags")
    FORWARDING_RULE_PORTS = StringListMetadataField("forwarding_rule_ports")
    FORWARDING_RULE_SOURCE_IP_RANGES = StringListMetadataField("forwarding_rule_source_ip_ranges")

    FIREWALL_ALLOW = DictListMetadataField("allow")
    FIREWALL_DENY = DictListMetadataField("deny")
    IAM_BINDINGS = DictListMetadataField("iam_bindings")
    CLOUD_SQL_AUTHORIZED_NETWORKS = DictListMetadataField("cloud_sql_authorized_networks")
    CLOUD_SQL_BACKUP_CONFIGURATION = DictMetadataField("cloud_sql_backup_configuration")
    CLOUD_SQL_IP_CONFIGURATION = DictMetadataField("cloud_sql_ip_configuration")
    GCS_VERSIONING_CONFIGURATION = DictMetadataField("gcs_versioning_configuration")
    GCS_ENCRYPTION_CONFIGURATION = DictMetadataField("gcs_encryption_configuration")
    NETWORK_INTERFACES = DictListMetadataField("network_interfaces")
    SERVICE_ACCOUNTS = DictListMetadataField("service_accounts")
    NAT_SUBNETWORKS = DictListMetadataField("nat_subnetworks")
    LABELS = DictMetadataField("labels")