from __future__ import annotations

from tfstride.resource_metadata import (
    BoolMetadataField,
    DictListMetadataField,
    DictMetadataField,
    OptionalIntMetadataField,
    OptionalStringMetadataField,
    StringListMetadataField,
)


class GcpResourceMetadata:
    """GCP-owned metadata fields preserved by the provider normalizers."""

    NAME = OptionalStringMetadataField("name")
    SELF_LINK = OptionalStringMetadataField("self_link")
    PROJECT = OptionalStringMetadataField("project")
    REGION = OptionalStringMetadataField("region")
    ZONE = OptionalStringMetadataField("zone")
    NETWORK = OptionalStringMetadataField("network")
    SUBNETWORK = OptionalStringMetadataField("subnetwork")
    CIDR_RANGE = OptionalStringMetadataField("cidr_range")
    MACHINE_TYPE = OptionalStringMetadataField("machine_type")
    DATABASE_VERSION = OptionalStringMetadataField("database_version")
    CLOUD_SQL_PRIVATE_NETWORK = OptionalStringMetadataField("cloud_sql_private_network")
    CLOUD_SQL_SSL_MODE = OptionalStringMetadataField("cloud_sql_ssl_mode")
    IAM_ROLE = OptionalStringMetadataField("iam_role")
    IAM_MEMBER = OptionalStringMetadataField("iam_member")
    IAM_CONDITION = DictMetadataField("iam_condition")
    CUSTOM_ROLE_ID = OptionalStringMetadataField("custom_role_id")
    CUSTOM_ROLE_STAGE = OptionalStringMetadataField("custom_role_stage")
    ORGANIZATION_ID = OptionalStringMetadataField("organization_id")
    FOLDER_ID = OptionalStringMetadataField("folder_id")
    ORG_POLICY_CONSTRAINT = OptionalStringMetadataField("org_policy_constraint")
    ORG_POLICY_SCOPE = OptionalStringMetadataField("org_policy_scope")
    ORG_POLICY_SCOPE_TYPE = OptionalStringMetadataField("org_policy_scope_type")
    BUCKET_NAME = OptionalStringMetadataField("bucket")
    SERVICE_ACCOUNT_ACCOUNT_ID = OptionalStringMetadataField("service_account_account_id")
    SERVICE_ACCOUNT_EMAIL = OptionalStringMetadataField("service_account_email")
    SERVICE_ACCOUNT_MEMBER = OptionalStringMetadataField("service_account_member")
    SERVICE_ACCOUNT_ID = OptionalStringMetadataField("service_account_id")
    SERVICE_ACCOUNT_REFERENCE = OptionalStringMetadataField("service_account_reference")
    CLOUD_RUN_SERVICE_REFERENCE = OptionalStringMetadataField("cloud_run_service_reference")
    CLOUD_FUNCTION_REFERENCE = OptionalStringMetadataField("cloud_function_reference")
    SERVERLESS_INGRESS = OptionalStringMetadataField("serverless_ingress")
    SERVICE_ACCOUNT_UNIQUE_ID = OptionalStringMetadataField("service_account_unique_id")
    SERVICE_ACCOUNT_KEY_ALGORITHM = OptionalStringMetadataField("service_account_key_algorithm")
    SERVICE_ACCOUNT_PUBLIC_KEY_TYPE = OptionalStringMetadataField("service_account_public_key_type")
    SERVICE_ACCOUNT_KEY_VALID_AFTER = OptionalStringMetadataField("valid_after")
    SERVICE_ACCOUNT_KEY_VALID_BEFORE = OptionalStringMetadataField("valid_before")
    SECRET_ID = OptionalStringMetadataField("secret_id")
    SECRET_REFERENCE = OptionalStringMetadataField("secret_reference")
    PUBSUB_TOPIC_REFERENCE = OptionalStringMetadataField("pubsub_topic_reference")
    PUBSUB_SUBSCRIPTION_REFERENCE = OptionalStringMetadataField("pubsub_subscription_reference")
    BIGQUERY_DATASET_ID = OptionalStringMetadataField("bigquery_dataset_id")
    BIGQUERY_DATASET_REFERENCE = OptionalStringMetadataField("bigquery_dataset_reference")
    BIGQUERY_TABLE_ID = OptionalStringMetadataField("bigquery_table_id")
    BIGQUERY_TABLE_REFERENCE = OptionalStringMetadataField("bigquery_table_reference")
    BIGQUERY_DEFAULT_KMS_KEY_NAME = OptionalStringMetadataField("bigquery_default_kms_key_name")
    KMS_CRYPTO_KEY_REFERENCE = OptionalStringMetadataField("kms_crypto_key_reference")
    KMS_KEY_RING = OptionalStringMetadataField("kms_key_ring")
    KMS_PURPOSE = OptionalStringMetadataField("kms_purpose")
    KMS_ROTATION_PERIOD = OptionalStringMetadataField("kms_rotation_period")
    PUBLIC_ACCESS_PREVENTION = OptionalStringMetadataField("public_access_prevention")
    GCS_DEFAULT_KMS_KEY_NAME = OptionalStringMetadataField("gcs_default_kms_key_name")
    ROUTE_DEST_RANGE = OptionalStringMetadataField("route_dest_range")
    ROUTE_NEXT_HOP_GATEWAY = OptionalStringMetadataField("route_next_hop_gateway")
    ROUTE_NEXT_HOP_INSTANCE = OptionalStringMetadataField("route_next_hop_instance")
    ROUTE_NEXT_HOP_IP = OptionalStringMetadataField("route_next_hop_ip")
    ROUTE_NEXT_HOP_ILB = OptionalStringMetadataField("route_next_hop_ilb")
    ROUTE_NEXT_HOP_VPN_TUNNEL = OptionalStringMetadataField("route_next_hop_vpn_tunnel")
    ROUTER_REFERENCE = OptionalStringMetadataField("router_reference")
    FIREWALL_POLICY_REFERENCE = OptionalStringMetadataField("firewall_policy_reference")
    FIREWALL_POLICY_PARENT = OptionalStringMetadataField("firewall_policy_parent")
    FIREWALL_POLICY_ATTACHMENT_TARGET = OptionalStringMetadataField("firewall_policy_attachment_target")
    FIREWALL_POLICY_ACTION = OptionalStringMetadataField("firewall_policy_action")
    FIREWALL_POLICY_DIRECTION = OptionalStringMetadataField("firewall_policy_direction")
    FIREWALL_DIRECTION = OptionalStringMetadataField("firewall_direction")
    FORWARDING_RULE_IP_ADDRESS = OptionalStringMetadataField("forwarding_rule_ip_address")
    FORWARDING_RULE_LOAD_BALANCING_SCHEME = OptionalStringMetadataField("forwarding_rule_load_balancing_scheme")
    FORWARDING_RULE_TARGET = OptionalStringMetadataField("forwarding_rule_target")
    FORWARDING_RULE_BACKEND_SERVICE = OptionalStringMetadataField("forwarding_rule_backend_service")
    LOAD_BALANCER_URL_MAP = OptionalStringMetadataField("load_balancer_url_map")
    LOAD_BALANCER_DEFAULT_SERVICE = OptionalStringMetadataField("load_balancer_default_service")
    LOAD_BALANCER_BACKEND_BUCKET_NAME = OptionalStringMetadataField("load_balancer_backend_bucket_name")
    LOAD_BALANCER_BACKEND_SERVICE_PROTOCOL = OptionalStringMetadataField("load_balancer_backend_service_protocol")
    LOAD_BALANCER_BACKEND_SERVICE_LOAD_BALANCING_SCHEME = OptionalStringMetadataField(
        "load_balancer_backend_service_load_balancing_scheme"
    )
    LOAD_BALANCER_NETWORK_ENDPOINT_TYPE = OptionalStringMetadataField("load_balancer_network_endpoint_type")
    GKE_ENDPOINT = OptionalStringMetadataField("gke_endpoint")
    GKE_WORKLOAD_IDENTITY_POOL = OptionalStringMetadataField("gke_workload_identity_pool")
    GKE_NODE_SERVICE_ACCOUNT = OptionalStringMetadataField("gke_node_service_account")
    GKE_NODE_METADATA_MODE = OptionalStringMetadataField("gke_node_metadata_mode")

    ROUTE_PRIORITY = OptionalIntMetadataField("route_priority")
    FIREWALL_PRIORITY = OptionalIntMetadataField("firewall_priority")
    FIREWALL_POLICY_PRIORITY = OptionalIntMetadataField("firewall_policy_priority")

    AUTO_CREATE_SUBNETWORKS = BoolMetadataField("auto_create_subnetworks")
    PRIVATE_IP_GOOGLE_ACCESS = BoolMetadataField("private_ip_google_access")
    UNIFORM_BUCKET_LEVEL_ACCESS = BoolMetadataField("uniform_bucket_level_access")
    GCS_VERSIONING_ENABLED = BoolMetadataField("gcs_versioning_enabled")
    SERVICE_ACCOUNT_DISABLED = BoolMetadataField("service_account_disabled")
    OS_LOGIN_ENABLED = BoolMetadataField("os_login_enabled")
    CLOUD_SQL_IPV4_ENABLED = BoolMetadataField("cloud_sql_ipv4_enabled")
    CLOUD_SQL_BACKUP_ENABLED = BoolMetadataField("cloud_sql_backup_enabled")
    CLOUD_SQL_POINT_IN_TIME_RECOVERY_ENABLED = BoolMetadataField("cloud_sql_point_in_time_recovery_enabled")
    CLOUD_SQL_REQUIRE_SSL = BoolMetadataField("cloud_sql_require_ssl")
    DELETION_PROTECTION = BoolMetadataField("deletion_protection")
    GKE_PRIVATE_ENDPOINT_ENABLED = BoolMetadataField("gke_private_endpoint_enabled")
    GKE_PRIVATE_NODES_ENABLED = BoolMetadataField("gke_private_nodes_enabled")
    GKE_WORKLOAD_IDENTITY_ENABLED = BoolMetadataField("gke_workload_identity_enabled")
    GKE_LEGACY_METADATA_ENDPOINTS_ENABLED = BoolMetadataField("gke_legacy_metadata_endpoints_enabled")
    CUSTOMER_MANAGED_ENCRYPTION = BoolMetadataField("customer_managed_encryption")
    FIREWALL_DISABLED = BoolMetadataField("firewall_disabled")
    FIREWALL_POLICY_DISABLED = BoolMetadataField("firewall_policy_disabled")
    FIREWALL_POLICY_ENABLE_LOGGING = BoolMetadataField("firewall_policy_enable_logging")
    FRONTED_BY_INTERNET_FACING_LOAD_BALANCER = BoolMetadataField(
        "fronted_by_internet_facing_load_balancer"
    )
    ORG_POLICY_ENFORCED = BoolMetadataField("org_policy_enforced")
    ORG_POLICY_INHERIT_FROM_PARENT = BoolMetadataField("org_policy_inherit_from_parent")
    ORG_POLICY_RESTORE_DEFAULT = BoolMetadataField("org_policy_restore_default")

    NETWORK_TAGS = StringListMetadataField("network_tags")
    IAM_MEMBERS = StringListMetadataField("iam_members")
    CUSTOM_ROLE_PERMISSIONS = StringListMetadataField("custom_role_permissions")
    RESOURCE_POLICY_SOURCE_ADDRESSES = StringListMetadataField("gcp_resource_policy_source_addresses")
    INTERNET_INGRESS_FIREWALLS = StringListMetadataField("internet_ingress_firewalls")
    FIREWALL_SOURCE_RANGES = StringListMetadataField("source_ranges")
    FIREWALL_DESTINATION_RANGES = StringListMetadataField("destination_ranges")
    FIREWALL_TARGET_TAGS = StringListMetadataField("target_tags")
    FIREWALL_SOURCE_TAGS = StringListMetadataField("source_tags")
    FIREWALL_TARGET_SERVICE_ACCOUNTS = StringListMetadataField("target_service_accounts")
    FIREWALL_POLICY_TARGET_RESOURCES = StringListMetadataField("firewall_policy_target_resources")
    FIREWALL_POLICY_TARGET_SERVICE_ACCOUNTS = StringListMetadataField("firewall_policy_target_service_accounts")
    FIREWALL_SOURCE_SERVICE_ACCOUNTS = StringListMetadataField("source_service_accounts")
    ROUTE_TAGS = StringListMetadataField("route_tags")
    FORWARDING_RULE_PORTS = StringListMetadataField("forwarding_rule_ports")
    FORWARDING_RULE_SOURCE_IP_RANGES = StringListMetadataField("forwarding_rule_source_ip_ranges")
    LOAD_BALANCER_SSL_CERTIFICATES = StringListMetadataField("load_balancer_ssl_certificates")
    INTERNET_FACING_LOAD_BALANCER_ADDRESSES = StringListMetadataField(
        "internet_facing_load_balancer_addresses"
    )
    GKE_NODE_OAUTH_SCOPES = StringListMetadataField("gke_node_oauth_scopes")
    ORG_POLICY_ALLOWED_VALUES = StringListMetadataField("org_policy_allowed_values")
    ORG_POLICY_DENIED_VALUES = StringListMetadataField("org_policy_denied_values")

    FIREWALL_ALLOW = DictListMetadataField("allow")
    FIREWALL_DENY = DictListMetadataField("deny")
    FIREWALL_POLICY_MATCH = DictMetadataField("firewall_policy_match")
    IAM_BINDINGS = DictListMetadataField("iam_bindings")
    LOAD_BALANCER_BACKENDS = DictListMetadataField("load_balancer_backends")
    LOAD_BALANCER_HOST_RULES = DictListMetadataField("load_balancer_host_rules")
    LOAD_BALANCER_PATH_MATCHERS = DictListMetadataField("load_balancer_path_matchers")
    LOAD_BALANCER_SERVERLESS_ENDPOINTS = DictListMetadataField("load_balancer_serverless_endpoints")
    LOAD_BALANCER_NETWORK_ENDPOINTS = DictListMetadataField("load_balancer_network_endpoints")
    LOAD_BALANCER_FRONTENDS = DictListMetadataField("load_balancer_frontends")
    LOAD_BALANCER_REACHABLE_BACKENDS = DictListMetadataField("load_balancer_reachable_backends")
    ORG_POLICY_RULES = DictListMetadataField("org_policy_rules")
    GKE_MASTER_AUTHORIZED_NETWORKS = DictListMetadataField("gke_master_authorized_networks")
    CLOUD_SQL_AUTHORIZED_NETWORKS = DictListMetadataField("cloud_sql_authorized_networks")
    CLOUD_SQL_BACKUP_CONFIGURATION = DictMetadataField("cloud_sql_backup_configuration")
    CLOUD_SQL_IP_CONFIGURATION = DictMetadataField("cloud_sql_ip_configuration")
    GCS_VERSIONING_CONFIGURATION = DictMetadataField("gcs_versioning_configuration")
    GCS_ENCRYPTION_CONFIGURATION = DictMetadataField("gcs_encryption_configuration")
    SERVICE_ACCOUNT_KEY_KEEPERS = DictMetadataField("keepers")
    NETWORK_INTERFACES = DictListMetadataField("network_interfaces")
    SERVICE_ACCOUNTS = DictListMetadataField("service_accounts")
    NAT_SUBNETWORKS = DictListMetadataField("nat_subnetworks")
    LABELS = DictMetadataField("labels")