from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tfstride.app import TfStride
from tfstride.config import ProjectConfigLoadError, load_project_config
from tfstride.filtering import FindingFilterLoadError, render_baseline
from tfstride.input.terraform_plan import TerraformPlanLoadError
from tfstride.models import Severity


INPUT_ERROR_EXIT_CODE = 2
POLICY_VIOLATION_EXIT_CODE = 3
SEVERITY_RANK = {
    Severity.LOW: 0,
    Severity.MEDIUM: 1,
    Severity.HIGH: 2,
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="tfstride",
        description="Analyze Terraform plan JSON and generate a deterministic cloud threat model report.",
    )
    parser.add_argument("plan", help="Path to Terraform plan JSON generated by `terraform show -json`.")
    parser.add_argument(
        "--config",
        help=(
            "Optional path to a `tfstride.toml` config file. If omitted, the CLI "
            "auto-discovers one from the current working directory or the plan directory."
        ),
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Optional path to write the markdown report. If omitted, the report is printed to stdout.",
    )
    parser.add_argument(
        "--json-output",
        help="Optional path to write a machine-readable JSON report alongside the markdown output.",
    )
    parser.add_argument(
        "--sarif-output",
        help="Optional path to write a SARIF 2.1.0 report alongside the markdown output.",
    )
    parser.add_argument(
        "--suppressions",
        help="Optional path to a JSON suppressions file used to exclude matching findings from reports and policy gating.",
    )
    parser.add_argument(
        "--baseline",
        help="Optional path to a JSON baseline file used to exclude previously accepted findings from reports and policy gating.",
    )
    parser.add_argument(
        "--baseline-output",
        help="Optional path to write a baseline JSON snapshot for the current unsuppressed findings.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress markdown output to stdout. File outputs, JSON outputs, and policy gate messages are still emitted.",
    )
    parser.add_argument(
        "--title",
        help="Optional custom report title.",
    )
    parser.add_argument(
        "--fail-on",
        choices=[severity.value for severity in (Severity.LOW, Severity.MEDIUM, Severity.HIGH)],
        help=(
            "Return a non-zero exit code when findings meet or exceed the given severity threshold. "
            "Useful for CI policy gating."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        project_config = load_project_config(path=args.config, plan_path=args.plan)
        engine = TfStride(rule_policy=project_config.rule_policy)
        title = args.title or project_config.title or "tfSTRIDE Threat Model Report"
        suppressions_path = args.suppressions or project_config.suppressions_path
        baseline_path = args.baseline or project_config.baseline_path
        fail_on = args.fail_on or (project_config.fail_on.value if project_config.fail_on else None)

        raw_result = engine.analyze_plan(args.plan, title=title)
        unsuppressed_result = engine.filter_findings(raw_result, suppressions_path=suppressions_path)
        if args.baseline_output:
            Path(args.baseline_output).write_text(render_baseline(unsuppressed_result.findings), encoding="utf-8")
        result = engine.filter_findings(
            raw_result,
            suppressions_path=suppressions_path,
            baseline_path=baseline_path,
        )
    except (TerraformPlanLoadError, FindingFilterLoadError, ProjectConfigLoadError) as exc:
        sys.stderr.write(f"Input error: {exc}\n")
        return INPUT_ERROR_EXIT_CODE

    report = engine.report_renderer.render(result)
    json_report = engine.json_renderer.render(result) if args.json_output else None
    sarif_report = engine.sarif_renderer.render(result) if args.sarif_output else None

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
    elif not args.quiet:
        sys.stdout.write(report)
        if not report.endswith("\n"):
            sys.stdout.write("\n")
    if args.json_output and json_report is not None:
        Path(args.json_output).write_text(json_report, encoding="utf-8")
    if args.sarif_output and sarif_report is not None:
        Path(args.sarif_output).write_text(sarif_report, encoding="utf-8")

    if not fail_on:
        return 0

    threshold = Severity(fail_on)
    violating_findings = [finding for finding in result.findings if _meets_or_exceeds(finding.severity, threshold)]
    if not violating_findings:
        return 0

    summary = ", ".join(
        f"{count} {severity.value}"
        for severity in (Severity.HIGH, Severity.MEDIUM, Severity.LOW)
        if (count := sum(1 for finding in violating_findings if finding.severity == severity))
    )
    sys.stderr.write(
        f"Policy gate failed: {len(violating_findings)} finding(s) meet or exceed `{threshold.value}`"
        f" ({summary}).\n"
    )
    return POLICY_VIOLATION_EXIT_CODE


def _meets_or_exceeds(severity: Severity, threshold: Severity) -> bool:
    return SEVERITY_RANK[severity] >= SEVERITY_RANK[threshold]
