from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from tfstride.analysis.rule_registry import DEFAULT_RULE_REGISTRY, RuleMetadata, RuleRegistry
from tfstride.app import TfStride
from tfstride.config import ProjectConfigLoadError, load_project_config
from tfstride.filtering import FindingFilterLoadError, render_baseline
from tfstride.input.terraform_plan import TerraformPlanLoadError
from tfstride.models import Severity


INPUT_ERROR_EXIT_CODE = 2
POLICY_VIOLATION_EXIT_CODE = 3
RULE_CATALOG_KIND = "tfstride-rule-catalog"
RULE_CATALOG_VERSION = "1.0"
SEVERITY_RANK = {
    Severity.LOW: 0,
    Severity.MEDIUM: 1,
    Severity.HIGH: 2,
}


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="tfstride",
        description="Analyze Terraform plan JSON and generate a deterministic cloud threat model report.",
    )
    parser.add_argument("plan", nargs="?", help="Path to Terraform plan JSON generated by `terraform show -json`.")
    parser.add_argument(
	    "--list-rules",
	    action="store_true",
	    help="List registered rules and exit without analyzing a Terraform plan.",
    )
    parser.add_argument(
	    "--json",
        action="store_true",
        help="Emit the rule listing as JSON. Only valid with `--list-rules`.",
	)
    parser.add_argument(
        "--config",
        help=(
            "Optional path to a `tfstride.toml` config file. If omitted, the CLI "
            "auto-discovers one from the current working directory or the plan directory."
        ),
    )
    parser.add_argument(
        "-o",
        "--output",
        help="Optional path to write the markdown report. If omitted, the report is printed to stdout.",
    )
    parser.add_argument(
        "--json-output",
        help="Optional path to write a machine-readable JSON report alongside the markdown output.",
    )
    parser.add_argument(
        "--sarif-output",
        help="Optional path to write a SARIF 2.1.0 report alongside the markdown output.",
    )
    parser.add_argument(
        "--suppressions",
        help="Optional path to a JSON suppressions file used to exclude matching findings from reports and policy gating.",
    )
    parser.add_argument(
        "--baseline",
        help="Optional path to a JSON baseline file used to exclude previously accepted findings from reports and policy gating.",
    )
    parser.add_argument(
        "--baseline-output",
        help="Optional path to write a baseline JSON snapshot for the current unsuppressed findings.",
    )
    parser.add_argument(
        "--quiet",
        action="store_true",
        help="Suppress markdown output to stdout. File outputs, JSON outputs, and policy gate messages are still emitted.",
    )
    parser.add_argument(
        "--title",
        help="Optional custom report title.",
    )
    parser.add_argument(
        "--fail-on",
        choices=[severity.value for severity in (Severity.LOW, Severity.MEDIUM, Severity.HIGH)],
        help=(
            "Return a non-zero exit code when findings meet or exceed the given severity threshold. "
            "Useful for CI policy gating."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.list_rules:
        if args.json:
	        sys.stdout.write(render_rule_catalog_json(DEFAULT_RULE_REGISTRY))
        else:
	        sys.stdout.write(render_rule_list(DEFAULT_RULE_REGISTRY))
        return 0
    if args.json:
	    parser.error("argument --json: only valid with --list-rules")

    plan_path = args.plan
    if plan_path is None:
        parser.error("the following arguments are required: plan")

    try:
        project_config = load_project_config(path=args.config, plan_path=plan_path)
        engine = TfStride(rule_policy=project_config.rule_policy)
        title = args.title or project_config.title or "tfSTRIDE Threat Model Report"
        suppressions_path = args.suppressions or project_config.suppressions_path
        baseline_path = args.baseline or project_config.baseline_path
        fail_on = args.fail_on or (project_config.fail_on.value if project_config.fail_on else None)

        raw_result = engine.analyze_plan(plan_path, title=title)
        unsuppressed_result = engine.filter_findings(raw_result, suppressions_path=suppressions_path)
        if args.baseline_output:
            Path(args.baseline_output).write_text(render_baseline(unsuppressed_result.findings), encoding="utf-8")
        result = engine.filter_findings(
            raw_result,
            suppressions_path=suppressions_path,
            baseline_path=baseline_path,
        )
    except (TerraformPlanLoadError, FindingFilterLoadError, ProjectConfigLoadError) as exc:
        sys.stderr.write(f"Input error: {exc}\n")
        return INPUT_ERROR_EXIT_CODE

    report = engine.render_markdown(result)
    json_report = engine.render_json(result) if args.json_output else None
    sarif_report = engine.render_sarif(result) if args.sarif_output else None

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
    elif not args.quiet:
        sys.stdout.write(report)
        if not report.endswith("\n"):
            sys.stdout.write("\n")
    if args.json_output and json_report is not None:
        Path(args.json_output).write_text(json_report, encoding="utf-8")
    if args.sarif_output and sarif_report is not None:
        Path(args.sarif_output).write_text(sarif_report, encoding="utf-8")

    if not fail_on:
        return 0

    threshold = Severity(fail_on)
    violating_findings = [finding for finding in result.findings if _meets_or_exceeds(finding.severity, threshold)]
    if not violating_findings:
        return 0

    summary = ", ".join(
        f"{count} {severity.value}"
        for severity in (Severity.HIGH, Severity.MEDIUM, Severity.LOW)
        if (count := sum(1 for finding in violating_findings if finding.severity == severity))
    )
    sys.stderr.write(
        f"Policy gate failed: {len(violating_findings)} finding(s) meet or exceed `{threshold.value}`"
        f" ({summary}).\n"
    )
    return POLICY_VIOLATION_EXIT_CODE


def _meets_or_exceeds(severity: Severity, threshold: Severity) -> bool:
    return SEVERITY_RANK[severity] >= SEVERITY_RANK[threshold]


def render_rule_list(registry: RuleRegistry = DEFAULT_RULE_REGISTRY) -> str:
    lines = ["tfSTRIDE Rules", ""]
    for rule in registry.rules():
        lines.extend(_render_rule(rule))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_rule_catalog_json(registry: RuleRegistry = DEFAULT_RULE_REGISTRY) -> str:
    payload = {
        "kind": RULE_CATALOG_KIND,
        "version": RULE_CATALOG_VERSION,
        "rules": [_rule_catalog_entry(rule) for rule in registry.rules()],
    }
    return json.dumps(payload, indent=2) + "\n"
	
	
def _rule_catalog_entry(rule: RuleMetadata) -> dict[str, object]:
    return {
        "rule_id": rule.rule_id,
        "title": rule.title,
        "category": rule.category.value,
        "enabled_by_default": rule.enabled_by_default,
        "tags": list(rule.tags),
        "severity_factors": list(rule.severity_factors),
        "recommended_mitigation": rule.recommended_mitigation,
    }
	
	
def _render_rule(rule: RuleMetadata) -> list[str]:
    return [
        f"- {rule.rule_id}",
        f"  Title: {rule.title}",
        f"  STRIDE: {rule.category.value}",
        f"  Enabled by default: {_format_yes_no(rule.enabled_by_default)}",
        f"  Tags: {_format_values(rule.tags)}",
        f"  Severity factors: {_format_values(rule.severity_factors)}",
        f"  Mitigation: {rule.recommended_mitigation}",
    ]
	
	
def _format_yes_no(value: bool) -> str:
    return "yes" if value else "no"
	
	
def _format_values(values: tuple[str, ...]) -> str:
    return ", ".join(values) if values else "none" 