from __future__ import annotations

import unittest
from typing import Any

from tfstride.providers.azure.metadata import AzureResourceMetadata
from tfstride.providers.contracts import DEFAULT_RESOURCE_METADATA_OWNERSHIP_CONTRACT
from tfstride.providers.metadata_ownership import (
    ProviderMetadataOwnershipError,
    ProviderMetadataWriteValidator,
)
from tfstride.resource_metadata import MetadataField, OptionalStringMetadataField


def _metadata_fields_by_name(namespace: type) -> dict[str, MetadataField[Any]]:
    return {name: value for name, value in vars(namespace).items() if isinstance(value, MetadataField)}


class AzureResourceMetadataTests(unittest.TestCase):
    def test_azure_metadata_namespace_matches_ownership_contract(self) -> None:
        contract = DEFAULT_RESOURCE_METADATA_OWNERSHIP_CONTRACT
        expected_fields = {
            "NAME",
            "STORAGE_ACCOUNT_ID",
            "STORAGE_ACCOUNT_REFERENCE",
            "RESOLVED_STORAGE_ACCOUNT_ADDRESS",
            "KEY_VAULT_ID",
            "APP_SERVICE_ID",
            "APP_SERVICE_PLAN_REFERENCE",
            "APP_SERVICE_VNET_INTEGRATION_SUBNET_ID",
            "AKS_CLUSTER_ID",
            "AKS_PRIVATE_CLUSTER_STATE",
            "AKS_PRIVATE_DNS_ZONE_ID",
            "AKS_AUTHORIZED_IP_RANGES_STATE",
            "AKS_API_SERVER_VNET_INTEGRATION_STATE",
            "AKS_API_SERVER_SUBNET_ID",
            "AKS_LOCAL_ACCOUNT_STATE",
            "AKS_RBAC_STATE",
            "AKS_AAD_RBAC_STATE",
            "AKS_AAD_MANAGED_STATE",
            "AKS_AAD_AZURE_RBAC_STATE",
            "AKS_AAD_TENANT_ID",
            "AKS_OIDC_ISSUER_STATE",
            "AKS_WORKLOAD_IDENTITY_STATE",
            "AKS_NETWORK_PLUGIN",
            "AKS_NETWORK_POLICY",
            "AKS_NETWORK_POLICY_STATE",
            "AKS_NETWORK_MODE",
            "AKS_OUTBOUND_TYPE",
            "AKS_LOAD_BALANCER_SKU",
            "AKS_KUBELET_IDENTITY_STATE",
            "AKS_KMS_STATE",
            "AKS_KMS_KEY_VAULT_KEY_ID",
            "AKS_OMS_AGENT_STATE",
            "AKS_LOG_ANALYTICS_WORKSPACE_ID",
            "AKS_DEFENDER_STATE",
            "AKS_AZURE_POLICY_STATE",
            "AKS_KUBERNETES_VERSION",
            "AKS_AUTOMATIC_CHANNEL_UPGRADE",
            "KEY_VAULT_REFERENCE",
            "RESOLVED_KEY_VAULT_ADDRESS",
            "TENANT_ID",
            "OBJECT_ID",
            "APPLICATION_ID",
            "ROLE_ASSIGNMENT_SCOPE",
            "ROLE_DEFINITION_NAME",
            "ROLE_DEFINITION_ID",
            "ROLE_DEFINITION_SCOPE",
            "PRINCIPAL_ID",
            "PRINCIPAL_TYPE",
            "RESOLVED_MANAGED_IDENTITY_ADDRESS",
            "RESOLVED_ROLE_DEFINITION_ADDRESS",
            "ROLE_ASSIGNMENT_SCOPE_KIND",
            "ROLE_ASSIGNMENT_TARGET_RESOURCE_ADDRESS",
            "ROLE_ASSIGNMENT_TARGET_RESOURCE_TYPE",
            "CLIENT_ID",
            "IDENTITY_TYPE",
            "ATTACHED_IDENTITY_REFERENCES",
            "MANAGED_IDENTITY_UNCERTAINTIES",
            "ROLE_ASSIGNMENT_BREADTH_SIGNALS",
            "ROLE_ASSIGNMENT_BREADTH_MITIGATIONS",
            "ROLE_DEFINITION_ASSIGNABLE_SCOPES",
            "ROLE_DEFINITION_ACTIONS",
            "ROLE_DEFINITION_NOT_ACTIONS",
            "ROLE_DEFINITION_DATA_ACTIONS",
            "ROLE_DEFINITION_NOT_DATA_ACTIONS",
            "ROLE_DEFINITION_BREADTH_SIGNALS",
            "ROLE_DEFINITION_BREADTH_MITIGATIONS",
            "ROLE_DEFINITION_UNCERTAINTIES",
            "PURGE_PROTECTION_ENABLED",
            "RBAC_AUTHORIZATION_ENABLED",
            "CUSTOM_ROLE_DEFINITION",
            "KEY_VAULT_RELATED_RESOURCE_ADDRESSES",
            "KEY_VAULT_NETWORK_IP_RULES",
            "KEY_VAULT_NETWORK_SUBNET_IDS",
            "KEY_VAULT_NETWORK_UNCERTAINTIES",
            "KEY_VAULT_AUTHORIZATION_UNCERTAINTIES",
            "KEY_VAULT_RECOVERY_UNCERTAINTIES",
            "KEY_VAULT_ACCESS_POLICIES",
            "KEY_VAULT_ROLE_ASSIGNMENTS",
            "MANAGED_IDENTITY_ROLE_ASSIGNMENTS",
            "ROLE_DEFINITION_PERMISSIONS",
            "CONTAINER_ACCESS_TYPE",
            "STORAGE_CUSTOMER_MANAGED_KEY_ID",
            "STORAGE_CUSTOMER_MANAGED_KEY_IDENTITY_ID",
            "MIN_TLS_VERSION",
            "FTPS_STATE",
            "NETWORK_DEFAULT_ACTION",
            "NETWORK_RULE_SOURCE_ADDRESS",
            "ALLOW_NESTED_ITEMS_TO_BE_PUBLIC",
            "SHARED_ACCESS_KEY_ENABLED",
            "STORAGE_INFRASTRUCTURE_ENCRYPTION_ENABLED",
            "STORAGE_BLOB_VERSIONING_ENABLED",
            "PUBLIC_NETWORK_ACCESS_ENABLED",
            "PUBLIC_NETWORK_FALLBACK_STATE",
            "PUBLIC_CONTAINER_ADDRESSES",
            "UNRESOLVED_STORAGE_ACCOUNT_REFERENCES",
            "STORAGE_POSTURE_UNCERTAINTIES",
            "STORAGE_BLOB_DELETE_RETENTION_DAYS",
            "STORAGE_CONTAINER_DELETE_RETENTION_DAYS",
            "STORAGE_BLOB_RESTORE_POLICY_DAYS",
            "APP_SERVICE_POSTURE_UNCERTAINTIES",
            "AKS_AUTHORIZED_IP_RANGES",
            "AKS_AAD_ADMIN_GROUP_OBJECT_IDS",
            "AKS_USER_ASSIGNED_IDENTITY_IDS",
            "AKS_POSTURE_UNCERTAINTIES",
            "LOCATION",
            "VIRTUAL_NETWORK_REFERENCE",
            "RESOLVED_VIRTUAL_NETWORK_ADDRESS",
            "NETWORK_SECURITY_GROUP_REFERENCE",
            "SUBNET_REFERENCE",
            "NETWORK_INTERFACE_REFERENCE",
            "PUBLIC_IP_ADDRESS",
            "VM_SIZE",
            "OS_TYPE",
            "DEFAULT_OUTBOUND_ACCESS_ENABLED",
            "IP_FORWARDING_ENABLED",
            "ADDRESS_SPACE",
            "ADDRESS_PREFIXES",
            "NETWORK_INTERFACE_REFERENCES",
            "PUBLIC_IP_REFERENCES",
            "RESOLVED_SUBNET_ADDRESSES",
            "RESOLVED_NETWORK_SECURITY_GROUP_ADDRESSES",
            "RESOLVED_NETWORK_INTERFACE_ADDRESSES",
            "RESOLVED_PUBLIC_IP_ADDRESSES",
            "ASSOCIATED_RESOURCE_ADDRESSES",
            "STANDALONE_RULE_ADDRESSES",
            "UNRESOLVED_RESOURCE_REFERENCES",
            "IP_CONFIGURATIONS",
            "NETWORK_SECURITY_RULES",
            "PUBLIC_COMPUTE_EXPOSURE_PATHS",
            "MSSQL_SERVER_ID",
            "MSSQL_FIREWALL_START_IP",
            "MSSQL_FIREWALL_END_IP",
            "MSSQL_VNET_SUBNET_ID",
            "MSSQL_SECURITY_ALERT_STATE",
            "MSSQL_POSTURE_UNCERTAINTIES",
            "MSSQL_FIREWALL_RULE_ADDRESSES",
            "MSSQL_VNET_RULE_ADDRESSES",
            "POSTGRESQL_SERVER_ID",
            "POSTGRESQL_FIREWALL_START_IP",
            "POSTGRESQL_FIREWALL_END_IP",
            "POSTGRESQL_SSL_MIN_PROTOCOL_VERSION",
            "POSTGRESQL_GEO_REDUNDANT_BACKUP_ENABLED",
            "POSTGRESQL_DELEGATED_SUBNET_ID",
            "POSTGRESQL_POSTURE_UNCERTAINTIES",
            "POSTGRESQL_CONFIG_NAME",
            "POSTGRESQL_CONFIG_VALUE",
            "POSTGRESQL_CONFIG_SERVER_ID",
            "PRIVATE_ENDPOINT_ID",
            "PRIVATE_DNS_ZONE_ID",
            "PRIVATE_DNS_ZONE_REFERENCE",
            "PRIVATE_DNS_ZONE_VIRTUAL_NETWORK_LINK_ID",
            "PRIVATE_DNS_ZONE_VIRTUAL_NETWORK_REFERENCE",
            "PRIVATE_DNS_ZONE_REGISTRATION_STATE",
            "PRIVATE_DNS_ZONE_GROUP_STATE",
            "PRIVATE_DNS_ZONE_IDS_STATE",
            "PRIVATE_CONNECTION_RESOURCE_IDS",
            "PRIVATE_ENDPOINT_SUBRESOURCE_NAMES",
            "PRIVATE_DNS_ZONE_GROUP_NAMES",
            "PRIVATE_DNS_ZONE_IDS",
            "PRIVATE_ENDPOINT_UNCERTAINTIES",
            "PRIVATE_DNS_ZONE_UNCERTAINTIES",
            "PRIVATE_SERVICE_CONNECTIONS",
            "PRIVATE_DNS_ZONE_GROUPS",
            "AKS_KUBELET_IDENTITIES",
            "AKS_MAINTENANCE_WINDOWS",
        }

        self.assertEqual(contract.provider_owned_fields["azure"], frozenset(expected_fields))
        self.assertEqual(set(_metadata_fields_by_name(AzureResourceMetadata)), expected_fields)

    def test_azure_metadata_namespace_builds_write_validator(self) -> None:
        validator = ProviderMetadataWriteValidator.build(
            provider="azure",
            namespace=AzureResourceMetadata,
        )

        validator.validate(AzureResourceMetadata.STORAGE_ACCOUNT_ID)
        with self.assertRaisesRegex(
            ProviderMetadataOwnershipError,
            "use a field from AzureResourceMetadata",
        ):
            validator.validate(OptionalStringMetadataField("unclassified"))


if __name__ == "__main__":
    unittest.main()
