from __future__ import annotations

import unittest

from tfstride.providers.aws.metadata import (
    AWS_SHARED_CORE_METADATA_FIELD_NAMES,
    AwsResourceMetadata,
)
from tfstride.providers.contracts import DEFAULT_RESOURCE_METADATA_OWNERSHIP_CONTRACT
from tfstride.resource_metadata import MetadataField, ResourceMetadata


def _metadata_field_names(namespace: type) -> set[str]:
    return {name for name, value in vars(namespace).items() if isinstance(value, MetadataField)}


class AwsResourceMetadataTests(unittest.TestCase):
    def test_aws_metadata_namespace_covers_classified_fields(self) -> None:
        ownership_contract = DEFAULT_RESOURCE_METADATA_OWNERSHIP_CONTRACT
        expected_fields = ownership_contract.provider_owned_fields["aws"] | AWS_SHARED_CORE_METADATA_FIELD_NAMES

        self.assertEqual(_metadata_field_names(AwsResourceMetadata), expected_fields)

    def test_aws_metadata_namespace_aliases_shared_core_fields_only(self) -> None:
        ownership_contract = DEFAULT_RESOURCE_METADATA_OWNERSHIP_CONTRACT
        aws_owned = ownership_contract.provider_owned_fields["aws"]

        for field_name in AWS_SHARED_CORE_METADATA_FIELD_NAMES:
            with self.subTest(field_name=field_name):
                self.assertIs(
                    getattr(AwsResourceMetadata, field_name),
                    getattr(ResourceMetadata, field_name),
                )

        for field_name in aws_owned:
            with self.subTest(field_name=field_name):
                self.assertFalse(hasattr(ResourceMetadata, field_name))

    def test_aws_metadata_provider_fields_keep_existing_metadata_keys(self) -> None:
        expected_keys = {
            "SECURITY_GROUP_ID": "security_group_id",
            "ROLE_REFERENCE": "role",
            "BUCKET_NAME": "bucket",
            "BUCKET_ACL": "acl",
            "POLICY_DOCUMENT": "policy_document",
            "PUBLIC_ACCESS_BLOCK": "public_access_block",
            "RESOURCE_POLICY_SOURCE_ADDRESSES": "resource_policy_source_addresses",
            "S3_VERSIONING_STATUS": "s3_versioning_status",
            "S3_VERSIONING_SOURCE_ADDRESS": "s3_versioning_source_address",
            "S3_ENCRYPTION_ALGORITHM": "s3_encryption_algorithm",
            "S3_KMS_MASTER_KEY_ID": "s3_kms_master_key_id",
            "S3_BUCKET_KEY_ENABLED_STATE": "s3_bucket_key_enabled_state",
            "S3_ENCRYPTION_SOURCE_ADDRESS": "s3_encryption_source_address",
            "S3_VERSIONING_CONFIGURATION": "s3_versioning_configuration",
            "S3_SERVER_SIDE_ENCRYPTION_CONFIGURATION": "s3_server_side_encryption_configuration",
            "S3_OBJECT_LOCK_ENABLED_STATE": "s3_object_lock_enabled_state",
            "S3_OBJECT_LOCK_DEFAULT_RETENTION_MODE": "s3_object_lock_default_retention_mode",
            "S3_OBJECT_LOCK_DEFAULT_RETENTION_DAYS": "s3_object_lock_default_retention_days",
            "S3_OBJECT_LOCK_DEFAULT_RETENTION_YEARS": "s3_object_lock_default_retention_years",
            "S3_OBJECT_LOCK_SOURCE_ADDRESS": "s3_object_lock_source_address",
            "S3_OBJECT_LOCK_CONFIGURATION": "s3_object_lock_configuration",
            "S3_LIFECYCLE_RULES": "s3_lifecycle_rules",
            "S3_LIFECYCLE_RULE_COUNT": "s3_lifecycle_rule_count",
            "S3_LIFECYCLE_SOURCE_ADDRESS": "s3_lifecycle_source_address",
            "S3_POSTURE_UNCERTAINTIES": "s3_posture_uncertainties",
            "CONTAINER_IMAGE_POSTURE_UNCERTAINTIES": "container_image_posture_uncertainties",
            "ECS_SECRET_POSTURE_UNCERTAINTIES": "ecs_secret_posture_uncertainties",
            "ECS_NETWORK_POSTURE_UNCERTAINTIES": "ecs_network_posture_uncertainties",
            "ECS_SECURITY_GROUP_REFERENCE_STATE": "ecs_security_group_reference_state",
            "ECS_SECRET_ACCESS_PATH_UNCERTAINTIES": "ecs_secret_access_path_uncertainties",
            "ECR_REPOSITORY_URL": "ecr_repository_url",
            "ECR_ENCRYPTION_TYPE": "ecr_encryption_type",
            "ECR_KMS_KEY": "ecr_kms_key",
            "ECR_ENCRYPTION_OWNERSHIP_STATE": "ecr_encryption_ownership_state",
            "ECR_IMAGE_TAG_MUTABILITY": "ecr_image_tag_mutability",
            "ECR_IMAGE_TAG_MUTABILITY_EXCLUSION_FILTERS": "ecr_image_tag_mutability_exclusion_filters",
            "ECR_REPOSITORY_SCAN_ON_PUSH_STATE": "ecr_repository_scan_on_push_state",
            "ECR_REGISTRY_SCAN_TYPE": "ecr_registry_scan_type",
            "ECR_REGISTRY_SCANNING_COVERAGE_STATE": "ecr_registry_scanning_coverage_state",
            "ECR_REGISTRY_SCANNING_RULES": "ecr_registry_scanning_rules",
            "ECR_POSTURE_UNCERTAINTIES": "ecr_posture_uncertainties",
            "ECR_WRITE_PATH_UNCERTAINTIES": "ecr_write_path_uncertainties",
            "RDS_PUBLICLY_ACCESSIBLE_STATE": "rds_publicly_accessible_state",
            "RDS_BACKUP_RETENTION_PERIOD": "rds_backup_retention_period",
            "RDS_DELETION_PROTECTION_STATE": "rds_deletion_protection_state",
            "RDS_MULTI_AZ_STATE": "rds_multi_az_state",
            "RDS_KMS_KEY_ID": "rds_kms_key_id",
            "RDS_POSTURE_UNCERTAINTIES": "rds_posture_uncertainties",
            "KMS_KEY_USAGE": "kms_key_usage",
            "KMS_KEY_SPEC": "kms_key_spec",
            "KMS_CUSTOMER_MASTER_KEY_SPEC": "kms_customer_master_key_spec",
            "KMS_ENABLE_KEY_ROTATION_STATE": "kms_enable_key_rotation_state",
            "KMS_DELETION_WINDOW_IN_DAYS": "kms_deletion_window_in_days",
            "KMS_POSTURE_UNCERTAINTIES": "kms_posture_uncertainties",
            "EKS_CLUSTER_ARN": "eks_cluster_arn",
            "EKS_CLUSTER_ROLE_ARN": "eks_cluster_role_arn",
            "EKS_ENDPOINT_PUBLIC_ACCESS_STATE": "eks_endpoint_public_access_state",
            "EKS_ENDPOINT_PRIVATE_ACCESS_STATE": "eks_endpoint_private_access_state",
            "EKS_PUBLIC_ACCESS_CIDRS": "eks_public_access_cidrs",
            "EKS_PUBLIC_ACCESS_CIDRS_STATE": "eks_public_access_cidrs_state",
            "EKS_CONTROL_PLANE_LOGGING_STATE": "eks_control_plane_logging_state",
            "EKS_ENABLED_CLUSTER_LOG_TYPES": "eks_enabled_cluster_log_types",
            "EKS_SECRETS_ENCRYPTION_STATE": "eks_secrets_encryption_state",
            "EKS_AUTHENTICATION_MODE": "eks_authentication_mode",
            "EKS_ADDON_NAME": "eks_addon_name",
            "EKS_ADDON_CLUSTER_NAME": "eks_addon_cluster_name",
            "EKS_ADDON_VERSION": "eks_addon_version",
            "EKS_ADDON_CONFIGURATION_VALUES": "eks_addon_configuration_values",
            "EKS_ADDON_CONFIGURATION_KEYS": "eks_addon_configuration_keys",
            "EKS_ADDON_PRESERVE_STATE": "eks_addon_preserve_state",
            "EKS_ADDON_SERVICE_ACCOUNT_ROLE_ARN": "eks_addon_service_account_role_arn",
            "EKS_ADDON_TARGET_CLASS": "eks_addon_target_class",
            "EKS_POSTURE_UNCERTAINTIES": "eks_posture_uncertainties",
            "LAMBDA_PACKAGE_TYPE": "lambda_package_type",
            "CONTAINER_IMAGE_REFERENCES": "container_image_references",
            "ECS_SECRET_REFERENCES": "ecs_secret_references",
            "ECS_SECRET_ACCESS_PATHS": "ecs_secret_access_paths",
            "ECR_WRITE_PATHS": "ecr_write_paths",
            "LAMBDA_FUNCTION_URL": "lambda_function_url",
            "LAMBDA_FUNCTION_URL_AUTHORIZATION_TYPE": "lambda_function_url_authorization_type",
            "LAMBDA_FUNCTION_URL_QUALIFIER": "lambda_function_url_qualifier",
            "LAMBDA_FUNCTION_URL_INVOKE_MODE": "lambda_function_url_invoke_mode",
            "LAMBDA_FUNCTION_URL_CORS": "lambda_function_url_cors",
            "LAMBDA_FUNCTION_URL_CORS_ALLOW_CREDENTIALS_STATE": ("lambda_function_url_cors_allow_credentials_state"),
            "LAMBDA_FUNCTION_URL_CORS_ALLOW_HEADERS": "lambda_function_url_cors_allow_headers",
            "LAMBDA_FUNCTION_URL_CORS_ALLOW_METHODS": "lambda_function_url_cors_allow_methods",
            "LAMBDA_FUNCTION_URL_CORS_ALLOW_ORIGINS": "lambda_function_url_cors_allow_origins",
            "LAMBDA_FUNCTION_URL_CORS_EXPOSE_HEADERS": "lambda_function_url_cors_expose_headers",
            "LAMBDA_FUNCTION_URL_CORS_MAX_AGE": "lambda_function_url_cors_max_age",
            "LAMBDA_FUNCTION_URL_POSTURE_UNCERTAINTIES": "lambda_function_url_posture_uncertainties",
            "API_GATEWAY_API_ID": "api_gateway_api_id",
            "API_GATEWAY_NAME": "api_gateway_name",
            "API_GATEWAY_DESCRIPTION": "api_gateway_description",
            "API_GATEWAY_PROTOCOL_TYPE": "api_gateway_protocol_type",
            "API_GATEWAY_API_ENDPOINT": "api_gateway_api_endpoint",
            "API_GATEWAY_EXECUTION_ARN": "api_gateway_execution_arn",
            "API_GATEWAY_EXECUTE_API_ENDPOINT_STATE": "api_gateway_execute_api_endpoint_state",
            "API_GATEWAY_PUBLIC_ENDPOINT_STATE": "api_gateway_public_endpoint_state",
            "API_GATEWAY_ROUTE_SELECTION_EXPRESSION": "api_gateway_route_selection_expression",
            "API_GATEWAY_ROUTE_KEY": "api_gateway_route_key",
            "API_GATEWAY_OPENAPI_BODY_STATE": "api_gateway_openapi_body_state",
            "API_GATEWAY_ENDPOINT_TYPES": "api_gateway_endpoint_types",
            "API_GATEWAY_VPC_ENDPOINT_IDS": "api_gateway_vpc_endpoint_ids",
            "API_GATEWAY_AUTHORIZATION_SCOPES": "api_gateway_authorization_scopes",
            "API_GATEWAY_AUTHORIZER_PROVIDER_ARNS": "api_gateway_authorizer_provider_arns",
            "UNRESOLVED_API_GATEWAY_API_IDS": "unresolved_api_gateway_api_ids",
            "API_GATEWAY_ENDPOINT_CONFIGURATION": "api_gateway_endpoint_configuration",
            "API_GATEWAY_CORS_CONFIGURATION": "api_gateway_cors_configuration",
            "API_GATEWAY_PARENT_API_ADDRESS": "api_gateway_parent_api_address",
            "API_GATEWAY_METHOD_RESOURCE_ID": "api_gateway_method_resource_id",
            "API_GATEWAY_METHOD_HTTP_METHOD": "api_gateway_method_http_method",
            "API_GATEWAY_AUTHORIZATION_TYPE": "api_gateway_authorization_type",
            "API_GATEWAY_AUTHORIZER_ID": "api_gateway_authorizer_id",
            "API_GATEWAY_STAGE_NAME": "api_gateway_stage_name",
            "API_GATEWAY_ACCESS_LOG_DESTINATION_ARN": "api_gateway_access_log_destination_arn",
            "API_GATEWAY_ACCESS_LOG_FORMAT": "api_gateway_access_log_format",
            "API_GATEWAY_AUTHORIZER_NAME": "api_gateway_authorizer_name",
            "API_GATEWAY_AUTHORIZER_TYPE": "api_gateway_authorizer_type",
            "API_GATEWAY_AUTHORIZER_URI": "api_gateway_authorizer_uri",
            "API_GATEWAY_AUTHORIZER_CREDENTIALS": "api_gateway_authorizer_credentials",
            "API_GATEWAY_IDENTITY_SOURCE": "api_gateway_identity_source",
            "API_GATEWAY_IDENTITY_VALIDATION_EXPRESSION": "api_gateway_identity_validation_expression",
            "API_GATEWAY_AUTHORIZER_RESULT_TTL": "api_gateway_authorizer_result_ttl",
            "API_GATEWAY_METHODS": "api_gateway_methods",
            "API_GATEWAY_STAGES": "api_gateway_stages",
            "API_GATEWAY_AUTHORIZERS": "api_gateway_authorizers",
            "API_GATEWAY_ROUTES": "api_gateway_routes",
            "API_GATEWAY_POSTURE_UNCERTAINTIES": "api_gateway_posture_uncertainties",
            "LOAD_BALANCER_LISTENER_PROTOCOL": "load_balancer_listener_protocol",
            "LOAD_BALANCER_LISTENER_CERTIFICATE_ARN": "load_balancer_listener_certificate_arn",
            "LOAD_BALANCER_LISTENER_SSL_POLICY": "load_balancer_listener_ssl_policy",
            "LOAD_BALANCER_LISTENER_TLS_UNCERTAINTIES": "load_balancer_listener_tls_uncertainties",
            "CLOUDFRONT_DISTRIBUTION_ID": "cloudfront_distribution_id",
            "CLOUDFRONT_DISTRIBUTION_ARN": "cloudfront_distribution_arn",
            "CLOUDFRONT_DOMAIN_NAME": "cloudfront_domain_name",
            "CLOUDFRONT_ENABLED_STATE": "cloudfront_enabled_state",
            "CLOUDFRONT_IPV6_ENABLED_STATE": "cloudfront_ipv6_enabled_state",
            "CLOUDFRONT_HTTP_VERSION": "cloudfront_http_version",
            "CLOUDFRONT_DEFAULT_ROOT_OBJECT": "cloudfront_default_root_object",
            "CLOUDFRONT_WEB_ACL_ID": "cloudfront_web_acl_id",
            "CLOUDFRONT_DEFAULT_VIEWER_PROTOCOL_POLICY": "cloudfront_default_viewer_protocol_policy",
            "CLOUDFRONT_VIEWER_CERTIFICATE_SOURCE": "cloudfront_viewer_certificate_source",
            "CLOUDFRONT_DEFAULT_CERTIFICATE_STATE": "cloudfront_default_certificate_state",
            "CLOUDFRONT_MINIMUM_PROTOCOL_VERSION": "cloudfront_minimum_protocol_version",
            "CLOUDFRONT_SSL_SUPPORT_METHOD": "cloudfront_ssl_support_method",
            "CLOUDFRONT_ACM_CERTIFICATE_ARN": "cloudfront_acm_certificate_arn",
            "CLOUDFRONT_IAM_CERTIFICATE_ID": "cloudfront_iam_certificate_id",
            "CLOUDFRONT_LOGGING_STATE": "cloudfront_logging_state",
            "CLOUDFRONT_LOGGING_BUCKET": "cloudfront_logging_bucket",
            "CLOUDFRONT_LOGGING_PREFIX": "cloudfront_logging_prefix",
            "CLOUDFRONT_ALIASES": "cloudfront_aliases",
            "CLOUDFRONT_ORIGIN_IDS": "cloudfront_origin_ids",
            "CLOUDFRONT_ORIGIN_DOMAIN_NAMES": "cloudfront_origin_domain_names",
            "CLOUDFRONT_DEFAULT_ALLOWED_METHODS": "cloudfront_default_allowed_methods",
            "CLOUDFRONT_DEFAULT_CACHED_METHODS": "cloudfront_default_cached_methods",
            "CLOUDFRONT_ORDERED_VIEWER_PROTOCOL_POLICIES": "cloudfront_ordered_viewer_protocol_policies",
            "CLOUDFRONT_POSTURE_UNCERTAINTIES": "cloudfront_posture_uncertainties",
            "CLOUDFRONT_VIEWER_CERTIFICATE": "cloudfront_viewer_certificate",
            "CLOUDFRONT_DEFAULT_CACHE_BEHAVIOR": "cloudfront_default_cache_behavior",
            "CLOUDFRONT_LOGGING_CONFIG": "cloudfront_logging_config",
            "CLOUDFRONT_ORIGINS": "cloudfront_origins",
            "CLOUDFRONT_ORDERED_CACHE_BEHAVIORS": "cloudfront_ordered_cache_behaviors",
            "WEB_ACL_ID": "web_acl_id",
            "WEB_ACL_NAME": "web_acl_name",
            "WEB_ACL_ARN": "web_acl_arn",
            "WEB_ACL_SCOPE": "web_acl_scope",
            "WEB_ACL_DEFAULT_ACTION": "web_acl_default_action",
            "WEB_ACL_DEFAULT_ACTION_EVIDENCE": "web_acl_default_action_evidence",
            "WEB_ACL_RULES": "web_acl_rules",
            "WEB_ACL_RULE_NAMES": "web_acl_rule_names",
            "WEB_ACL_ASSOCIATION_RESOURCE_ARN": "web_acl_association_resource_arn",
            "WEB_ACL_ASSOCIATION_WEB_ACL_ARN": "web_acl_association_web_acl_arn",
            "EDGE_PROTECTION_POSTURE_UNCERTAINTIES": "edge_protection_posture_uncertainties",
            "AUDIT_DETECTION_POSTURE_UNCERTAINTIES": "audit_detection_posture_uncertainties",
            "IAM_ASSIGNMENT_POSTURE_UNCERTAINTIES": "iam_assignment_posture_uncertainties",
            "OIDC_PROVIDER_URL": "oidc_provider_url",
            "OIDC_PROVIDER_ARN": "oidc_provider_arn",
            "OIDC_PROVIDER_CLIENT_IDS": "oidc_provider_client_ids",
            "OIDC_PROVIDER_THUMBPRINTS": "oidc_provider_thumbprints",
            "OIDC_PROVIDER_POSTURE_UNCERTAINTIES": "oidc_provider_posture_uncertainties",
            "CLOUDTRAIL_S3_BUCKET_NAME": "cloudtrail_s3_bucket_name",
            "CLOUDTRAIL_S3_KEY_PREFIX": "cloudtrail_s3_key_prefix",
            "CLOUDTRAIL_KMS_KEY_ID": "cloudtrail_kms_key_id",
            "CLOUDTRAIL_CLOUDWATCH_LOGS_GROUP_ARN": "cloudtrail_cloudwatch_logs_group_arn",
            "CLOUDTRAIL_CLOUDWATCH_LOGS_ROLE_ARN": "cloudtrail_cloudwatch_logs_role_arn",
            "CLOUDTRAIL_ENABLE_LOGGING_STATE": "cloudtrail_enable_logging_state",
            "CLOUDTRAIL_LOG_FILE_VALIDATION_STATE": "cloudtrail_log_file_validation_state",
            "CLOUDTRAIL_MULTI_REGION_STATE": "cloudtrail_multi_region_state",
            "CLOUDTRAIL_GLOBAL_SERVICE_EVENTS_STATE": "cloudtrail_global_service_events_state",
            "CLOUDTRAIL_ORGANIZATION_TRAIL_STATE": "cloudtrail_organization_trail_state",
            "CLOUDTRAIL_EVENT_SELECTORS": "cloudtrail_event_selectors",
            "PRIVILEGED_ACCESS_GRANTS": "privileged_access_grants",
            "CLOUDTRAIL_INSIGHT_SELECTORS": "cloudtrail_insight_selectors",
            "GUARDDUTY_ENABLE_STATE": "guardduty_enable_state",
            "GUARDDUTY_FINDING_PUBLISHING_FREQUENCY": "guardduty_finding_publishing_frequency",
            "GUARDDUTY_DATASOURCES": "guardduty_datasources",
            "GUARDDUTY_FEATURES": "guardduty_features",
            "SECURITYHUB_ENABLE_DEFAULT_STANDARDS_STATE": "securityhub_enable_default_standards_state",
            "SECURITYHUB_AUTO_ENABLE_CONTROLS_STATE": "securityhub_auto_enable_controls_state",
            "SECURITYHUB_CONTROL_FINDING_GENERATOR": "securityhub_control_finding_generator",
            "CONFIG_RECORDER_NAME": "config_recorder_name",
            "CONFIG_RECORDER_ROLE_ARN": "config_recorder_role_arn",
            "CONFIG_RECORDER_ALL_SUPPORTED_STATE": "config_recorder_all_supported_state",
            "CONFIG_RECORDER_INCLUDE_GLOBAL_RESOURCE_TYPES_STATE": "config_recorder_include_global_resource_types_state",
            "CONFIG_RECORDER_RESOURCE_TYPES": "config_recorder_resource_types",
            "CONFIG_RECORDER_RECORDING_STRATEGY_USE_ONLY": "config_recorder_recording_strategy_use_only",
            "CONFIG_RECORDER_RECORDING_GROUP": "config_recorder_recording_group",
            "CONFIG_RECORDER_RECORDING_STRATEGY": "config_recorder_recording_strategy",
            "CONFIG_RECORDER_STATUS_NAME": "config_recorder_status_name",
            "CONFIG_RECORDER_IS_ENABLED_STATE": "config_recorder_is_enabled_state",
            "CONFIG_DELIVERY_CHANNEL_NAME": "config_delivery_channel_name",
            "CONFIG_DELIVERY_CHANNEL_S3_BUCKET_NAME": "config_delivery_channel_s3_bucket_name",
            "CONFIG_DELIVERY_CHANNEL_S3_KEY_PREFIX": "config_delivery_channel_s3_key_prefix",
            "CONFIG_DELIVERY_CHANNEL_SNS_TOPIC_ARN": "config_delivery_channel_sns_topic_arn",
            "ACCESS_ANALYZER_NAME": "access_analyzer_name",
            "ACCESS_ANALYZER_TYPE": "access_analyzer_type",
            "ACCESS_ANALYZER_STATUS": "access_analyzer_status",
            "ACCESS_ANALYZER_ARN": "access_analyzer_arn",
            "ACCESS_ANALYZER_CONFIGURATION": "access_analyzer_configuration",
            "MACIE_ACCOUNT_STATUS": "macie_account_status",
            "MACIE_ACCOUNT_STATUS_STATE": "macie_account_status_state",
            "MACIE_FINDING_PUBLISHING_FREQUENCY": "macie_finding_publishing_frequency",
            "VPC_ENDPOINT_ID": "vpc_endpoint_id",
            "VPC_ENDPOINT_SERVICE_NAME": "vpc_endpoint_service_name",
            "VPC_ENDPOINT_SERVICE_FAMILY": "vpc_endpoint_service_family",
            "VPC_ENDPOINT_TYPE": "vpc_endpoint_type",
            "VPC_ENDPOINT_VPC_ID": "vpc_endpoint_vpc_id",
            "VPC_ENDPOINT_ROUTE_TABLE_IDS": "vpc_endpoint_route_table_ids",
            "VPC_ENDPOINT_SUBNET_IDS": "vpc_endpoint_subnet_ids",
            "VPC_ENDPOINT_SECURITY_GROUP_IDS": "vpc_endpoint_security_group_ids",
            "VPC_ENDPOINT_PRIVATE_DNS_ENABLED_STATE": "vpc_endpoint_private_dns_enabled_state",
            "VPC_ENDPOINT_POLICY_DOCUMENT": "vpc_endpoint_policy_document",
            "VPC_ENDPOINT_DNS_ENTRIES": "vpc_endpoint_dns_entries",
            "VPC_ENDPOINT_DNS_NAMES": "vpc_endpoint_dns_names",
            "VPC_ENDPOINT_POSTURE_UNCERTAINTIES": "vpc_endpoint_posture_uncertainties",
            "FLOW_LOG_ID": "flow_log_id",
            "FLOW_LOG_TARGET_TYPE": "flow_log_target_type",
            "FLOW_LOG_TARGET_ID": "flow_log_target_id",
            "FLOW_LOG_TRAFFIC_TYPE": "flow_log_traffic_type",
            "FLOW_LOG_DESTINATION_TYPE": "flow_log_destination_type",
            "FLOW_LOG_DESTINATION": "flow_log_destination",
            "FLOW_LOG_LOG_GROUP_NAME": "flow_log_log_group_name",
            "FLOW_LOG_IAM_ROLE_ARN": "flow_log_iam_role_arn",
            "FLOW_LOG_MAX_AGGREGATION_INTERVAL": "flow_log_max_aggregation_interval",
            "FLOW_LOG_DESTINATION_OPTIONS": "flow_log_destination_options",
            "FLOW_LOG_POSTURE_UNCERTAINTIES": "flow_log_posture_uncertainties",
        }

        for field_name, key in expected_keys.items():
            with self.subTest(field_name=field_name):
                self.assertEqual(getattr(AwsResourceMetadata, field_name).key, key)


if __name__ == "__main__":
    unittest.main()
