from __future__ import annotations

import argparse
import sys
from pathlib import Path

from cloud_threat_modeler.app import CloudThreatModeler


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="cloud-threat-modeler",
        description="Analyze Terraform plan JSON and generate a deterministic cloud threat model report.",
    )
    parser.add_argument("plan", help="Path to Terraform plan JSON generated by `terraform show -json`.")
    parser.add_argument(
        "-o",
        "--output",
        help="Optional path to write the markdown report. If omitted, the report is printed to stdout.",
    )
    parser.add_argument(
        "--title",
        default="Cloud Threat Model Report",
        help="Optional custom report title.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    engine = CloudThreatModeler()
    report = engine.render_markdown_report(args.plan, title=args.title)

    if args.output:
        Path(args.output).write_text(report, encoding="utf-8")
    else:
        sys.stdout.write(report)
        if not report.endswith("\n"):
            sys.stdout.write("\n")
    return 0
