from __future__ import annotations

from tfstride.resource_metadata import (
    BoolMetadataField,
    DictListMetadataField,
    OptionalStringMetadataField,
    StringListMetadataField,
)


class AzureResourceMetadata:
    """Azure-owned metadata fields preserved by provider normalizers."""

    NAME = OptionalStringMetadataField("name")
    STORAGE_ACCOUNT_ID = OptionalStringMetadataField("storage_account_id")
    STORAGE_ACCOUNT_REFERENCE = OptionalStringMetadataField("storage_account_reference")
    RESOLVED_STORAGE_ACCOUNT_ADDRESS = OptionalStringMetadataField("resolved_storage_account_address")
    KEY_VAULT_ID = OptionalStringMetadataField("key_vault_id")
    KEY_VAULT_REFERENCE = OptionalStringMetadataField("key_vault_reference")
    RESOLVED_KEY_VAULT_ADDRESS = OptionalStringMetadataField("resolved_key_vault_address")
    CONTAINER_ACCESS_TYPE = OptionalStringMetadataField("container_access_type")
    MIN_TLS_VERSION = OptionalStringMetadataField("min_tls_version")
    NETWORK_DEFAULT_ACTION = OptionalStringMetadataField("network_default_action")
    NETWORK_RULE_SOURCE_ADDRESS = OptionalStringMetadataField("network_rule_source_address")
    LOCATION = OptionalStringMetadataField("location")
    VIRTUAL_NETWORK_REFERENCE = OptionalStringMetadataField("virtual_network_reference")
    RESOLVED_VIRTUAL_NETWORK_ADDRESS = OptionalStringMetadataField("resolved_virtual_network_address")
    NETWORK_SECURITY_GROUP_REFERENCE = OptionalStringMetadataField("network_security_group_reference")
    SUBNET_REFERENCE = OptionalStringMetadataField("subnet_reference")
    NETWORK_INTERFACE_REFERENCE = OptionalStringMetadataField("network_interface_reference")
    PUBLIC_IP_ADDRESS = OptionalStringMetadataField("public_ip_address")
    VM_SIZE = OptionalStringMetadataField("vm_size")
    OS_TYPE = OptionalStringMetadataField("os_type")
    TENANT_ID = OptionalStringMetadataField("tenant_id")
    OBJECT_ID = OptionalStringMetadataField("object_id")
    APPLICATION_ID = OptionalStringMetadataField("application_id")
    ROLE_ASSIGNMENT_SCOPE = OptionalStringMetadataField("role_assignment_scope")
    ROLE_DEFINITION_NAME = OptionalStringMetadataField("role_definition_name")
    ROLE_DEFINITION_ID = OptionalStringMetadataField("role_definition_id")
    PRINCIPAL_ID = OptionalStringMetadataField("principal_id")
    PRINCIPAL_TYPE = OptionalStringMetadataField("principal_type")
    RESOLVED_MANAGED_IDENTITY_ADDRESS = OptionalStringMetadataField("resolved_managed_identity_address")
    ROLE_ASSIGNMENT_SCOPE_KIND = OptionalStringMetadataField("role_assignment_scope_kind")
    ROLE_ASSIGNMENT_TARGET_RESOURCE_ADDRESS = OptionalStringMetadataField("role_assignment_target_resource_address")
    ROLE_ASSIGNMENT_TARGET_RESOURCE_TYPE = OptionalStringMetadataField("role_assignment_target_resource_type")
    CLIENT_ID = OptionalStringMetadataField("client_id")
    IDENTITY_TYPE = OptionalStringMetadataField("identity_type")

    ALLOW_NESTED_ITEMS_TO_BE_PUBLIC = BoolMetadataField("allow_nested_items_to_be_public")
    SHARED_ACCESS_KEY_ENABLED = BoolMetadataField("shared_access_key_enabled")
    PUBLIC_NETWORK_ACCESS_ENABLED = BoolMetadataField("public_network_access_enabled")
    DEFAULT_OUTBOUND_ACCESS_ENABLED = BoolMetadataField("default_outbound_access_enabled", default=True)
    IP_FORWARDING_ENABLED = BoolMetadataField("ip_forwarding_enabled")
    PURGE_PROTECTION_ENABLED = BoolMetadataField("purge_protection_enabled")
    RBAC_AUTHORIZATION_ENABLED = BoolMetadataField("rbac_authorization_enabled")

    PUBLIC_CONTAINER_ADDRESSES = StringListMetadataField("public_container_addresses")
    UNRESOLVED_STORAGE_ACCOUNT_REFERENCES = StringListMetadataField("unresolved_storage_account_references")
    STORAGE_POSTURE_UNCERTAINTIES = StringListMetadataField("storage_posture_uncertainties")
    KEY_VAULT_RELATED_RESOURCE_ADDRESSES = StringListMetadataField("key_vault_related_resource_addresses")
    KEY_VAULT_NETWORK_IP_RULES = StringListMetadataField("key_vault_network_ip_rules")
    KEY_VAULT_NETWORK_SUBNET_IDS = StringListMetadataField("key_vault_network_subnet_ids")
    KEY_VAULT_NETWORK_UNCERTAINTIES = StringListMetadataField("key_vault_network_uncertainties")
    KEY_VAULT_AUTHORIZATION_UNCERTAINTIES = StringListMetadataField("key_vault_authorization_uncertainties")
    KEY_VAULT_RECOVERY_UNCERTAINTIES = StringListMetadataField("key_vault_recovery_uncertainties")
    ATTACHED_IDENTITY_REFERENCES = StringListMetadataField("attached_identity_references")
    MANAGED_IDENTITY_UNCERTAINTIES = StringListMetadataField("managed_identity_uncertainties")
    ROLE_ASSIGNMENT_BREADTH_SIGNALS = StringListMetadataField("role_assignment_breadth_signals")
    ADDRESS_SPACE = StringListMetadataField("address_space")
    ADDRESS_PREFIXES = StringListMetadataField("address_prefixes")
    NETWORK_INTERFACE_REFERENCES = StringListMetadataField("network_interface_references")
    PUBLIC_IP_REFERENCES = StringListMetadataField("public_ip_references")
    RESOLVED_SUBNET_ADDRESSES = StringListMetadataField("resolved_subnet_addresses")
    RESOLVED_NETWORK_SECURITY_GROUP_ADDRESSES = StringListMetadataField("resolved_network_security_group_addresses")
    RESOLVED_NETWORK_INTERFACE_ADDRESSES = StringListMetadataField("resolved_network_interface_addresses")
    RESOLVED_PUBLIC_IP_ADDRESSES = StringListMetadataField("resolved_public_ip_addresses")
    ASSOCIATED_RESOURCE_ADDRESSES = StringListMetadataField("associated_resource_addresses")
    STANDALONE_RULE_ADDRESSES = StringListMetadataField("standalone_rule_addresses")
    UNRESOLVED_RESOURCE_REFERENCES = StringListMetadataField("unresolved_resource_references")

    IP_CONFIGURATIONS = DictListMetadataField("ip_configurations")
    NETWORK_SECURITY_RULES = DictListMetadataField("network_security_rules")
    PUBLIC_COMPUTE_EXPOSURE_PATHS = DictListMetadataField("public_compute_exposure_paths")
    KEY_VAULT_ACCESS_POLICIES = DictListMetadataField("key_vault_access_policies")
    KEY_VAULT_ROLE_ASSIGNMENTS = DictListMetadataField("key_vault_role_assignments")
    MANAGED_IDENTITY_ROLE_ASSIGNMENTS = DictListMetadataField("managed_identity_role_assignments")
