from __future__ import annotations

from tfstride.resource_metadata import (
    BoolMetadataField,
    DictListMetadataField,
    DictMetadataField,
    OptionalIntMetadataField,
    OptionalStringMetadataField,
    StringListMetadataField,
)


class AzureResourceMetadata:
    """Azure-owned metadata fields preserved by provider normalizers."""

    NAME = OptionalStringMetadataField("name")
    STORAGE_ACCOUNT_ID = OptionalStringMetadataField("storage_account_id")
    SERVICE_BUS_NAMESPACE_ID = OptionalStringMetadataField("service_bus_namespace_id")
    SERVICE_BUS_NAMESPACE_REFERENCE = OptionalStringMetadataField("service_bus_namespace_reference")
    RESOLVED_SERVICE_BUS_NAMESPACE_ADDRESS = OptionalStringMetadataField("resolved_service_bus_namespace_address")
    SERVICE_BUS_SKU = OptionalStringMetadataField("service_bus_sku")
    SERVICE_BUS_TIER = OptionalStringMetadataField("service_bus_tier")
    SERVICE_BUS_LOCAL_AUTH_STATE = OptionalStringMetadataField("service_bus_local_auth_state")
    SERVICE_BUS_CUSTOMER_MANAGED_KEY_STATE = OptionalStringMetadataField("service_bus_customer_managed_key_state")
    SERVICE_BUS_KEY_VAULT_KEY_ID = OptionalStringMetadataField("service_bus_key_vault_key_id")
    SERVICE_BUS_NETWORK_RULE_SOURCE_ADDRESS = OptionalStringMetadataField("service_bus_network_rule_source_address")
    SERVICE_BUS_CUSTOMER_MANAGED_KEY_SOURCE_ADDRESS = OptionalStringMetadataField(
        "service_bus_customer_managed_key_source_address"
    )
    CONTAINER_REGISTRY_ID = OptionalStringMetadataField("container_registry_id")
    CONTAINER_REGISTRY_SKU = OptionalStringMetadataField("container_registry_sku")
    CONTAINER_REGISTRY_LOGIN_SERVER = OptionalStringMetadataField("container_registry_login_server")
    CONTAINER_REGISTRY_PREMIUM_TIER_STATE = OptionalStringMetadataField("container_registry_premium_tier_state")
    CONTAINER_REGISTRY_ADMIN_STATE = OptionalStringMetadataField("container_registry_admin_state")
    CONTAINER_REGISTRY_ANONYMOUS_PULL_STATE = OptionalStringMetadataField("container_registry_anonymous_pull_state")
    CONTAINER_REGISTRY_CUSTOMER_MANAGED_KEY_STATE = OptionalStringMetadataField(
        "container_registry_customer_managed_key_state"
    )
    CONTAINER_REGISTRY_KEY_VAULT_KEY_ID = OptionalStringMetadataField("container_registry_key_vault_key_id")
    CONTAINER_REGISTRY_ENCRYPTION_IDENTITY_CLIENT_ID = OptionalStringMetadataField(
        "container_registry_encryption_identity_client_id"
    )
    CONTAINER_REGISTRY_RETENTION_STATE = OptionalStringMetadataField("container_registry_retention_state")
    CONTAINER_REGISTRY_EXPORT_POLICY_STATE = OptionalStringMetadataField("container_registry_export_policy_state")
    CONTAINER_REGISTRY_QUARANTINE_POLICY_STATE = OptionalStringMetadataField(
        "container_registry_quarantine_policy_state"
    )
    CONTAINER_REGISTRY_TRUST_POLICY_STATE = OptionalStringMetadataField("container_registry_trust_policy_state")
    CONTAINER_REGISTRY_ZONE_REDUNDANCY_STATE = OptionalStringMetadataField("container_registry_zone_redundancy_state")
    CONTAINER_REGISTRY_DATA_ENDPOINT_STATE = OptionalStringMetadataField("container_registry_data_endpoint_state")
    CONTAINER_REGISTRY_NETWORK_RULE_BYPASS_OPTION = OptionalStringMetadataField(
        "container_registry_network_rule_bypass_option"
    )
    STORAGE_ACCOUNT_REFERENCE = OptionalStringMetadataField("storage_account_reference")
    RESOLVED_STORAGE_ACCOUNT_ADDRESS = OptionalStringMetadataField("resolved_storage_account_address")
    KEY_VAULT_ID = OptionalStringMetadataField("key_vault_id")
    KEY_VAULT_URI = OptionalStringMetadataField("key_vault_uri")
    APP_SERVICE_ID = OptionalStringMetadataField("app_service_id")
    APP_SERVICE_PLAN_REFERENCE = OptionalStringMetadataField("app_service_plan_reference")
    APP_SERVICE_KEY_VAULT_REFERENCE_IDENTITY_ID = OptionalStringMetadataField(
        "app_service_key_vault_reference_identity_id"
    )
    APP_SERVICE_VNET_INTEGRATION_SUBNET_ID = OptionalStringMetadataField("app_service_vnet_integration_subnet_id")
    APP_SERVICE_IP_RESTRICTION_DEFAULT_ACTION = OptionalStringMetadataField("app_service_ip_restriction_default_action")
    APP_SERVICE_SCM_IP_RESTRICTION_DEFAULT_ACTION = OptionalStringMetadataField(
        "app_service_scm_ip_restriction_default_action"
    )
    APP_SERVICE_SCM_USE_MAIN_IP_RESTRICTION = BoolMetadataField("app_service_scm_use_main_ip_restriction")
    AKS_CLUSTER_ID = OptionalStringMetadataField("aks_cluster_id")
    AKS_PRIVATE_CLUSTER_STATE = OptionalStringMetadataField("aks_private_cluster_state")
    AKS_PRIVATE_DNS_ZONE_ID = OptionalStringMetadataField("aks_private_dns_zone_id")
    AKS_AUTHORIZED_IP_RANGES_STATE = OptionalStringMetadataField("aks_authorized_ip_ranges_state")
    AKS_API_SERVER_VNET_INTEGRATION_STATE = OptionalStringMetadataField("aks_api_server_vnet_integration_state")
    AKS_API_SERVER_SUBNET_ID = OptionalStringMetadataField("aks_api_server_subnet_id")
    AKS_LOCAL_ACCOUNT_STATE = OptionalStringMetadataField("aks_local_account_state")
    AKS_RBAC_STATE = OptionalStringMetadataField("aks_rbac_state")
    AKS_AAD_RBAC_STATE = OptionalStringMetadataField("aks_aad_rbac_state")
    AKS_AAD_MANAGED_STATE = OptionalStringMetadataField("aks_aad_managed_state")
    AKS_AAD_AZURE_RBAC_STATE = OptionalStringMetadataField("aks_aad_azure_rbac_state")
    AKS_AAD_TENANT_ID = OptionalStringMetadataField("aks_aad_tenant_id")
    AKS_OIDC_ISSUER_STATE = OptionalStringMetadataField("aks_oidc_issuer_state")
    AKS_WORKLOAD_IDENTITY_STATE = OptionalStringMetadataField("aks_workload_identity_state")
    AKS_NETWORK_PLUGIN = OptionalStringMetadataField("aks_network_plugin")
    AKS_NETWORK_POLICY = OptionalStringMetadataField("aks_network_policy")
    AKS_NETWORK_POLICY_STATE = OptionalStringMetadataField("aks_network_policy_state")
    AKS_NETWORK_MODE = OptionalStringMetadataField("aks_network_mode")
    AKS_OUTBOUND_TYPE = OptionalStringMetadataField("aks_outbound_type")
    AKS_LOAD_BALANCER_SKU = OptionalStringMetadataField("aks_load_balancer_sku")
    AKS_KUBELET_IDENTITY_STATE = OptionalStringMetadataField("aks_kubelet_identity_state")
    AKS_KMS_STATE = OptionalStringMetadataField("aks_kms_state")
    AKS_KMS_KEY_VAULT_KEY_ID = OptionalStringMetadataField("aks_kms_key_vault_key_id")
    AKS_OMS_AGENT_STATE = OptionalStringMetadataField("aks_oms_agent_state")
    AKS_LOG_ANALYTICS_WORKSPACE_ID = OptionalStringMetadataField("aks_log_analytics_workspace_id")
    AKS_DEFENDER_STATE = OptionalStringMetadataField("aks_defender_state")
    AKS_AZURE_POLICY_STATE = OptionalStringMetadataField("aks_azure_policy_state")
    AKS_KUBERNETES_VERSION = OptionalStringMetadataField("aks_kubernetes_version")
    AKS_AUTOMATIC_CHANNEL_UPGRADE = OptionalStringMetadataField("aks_automatic_channel_upgrade")
    DIAGNOSTIC_SETTING_ID = OptionalStringMetadataField("diagnostic_setting_id")
    DIAGNOSTIC_SETTING_NAME = OptionalStringMetadataField("diagnostic_setting_name")
    DIAGNOSTIC_TARGET_RESOURCE_ID = OptionalStringMetadataField("diagnostic_target_resource_id")
    DIAGNOSTIC_LOG_ANALYTICS_WORKSPACE_ID = OptionalStringMetadataField("diagnostic_log_analytics_workspace_id")
    DIAGNOSTIC_STORAGE_ACCOUNT_ID = OptionalStringMetadataField("diagnostic_storage_account_id")
    DIAGNOSTIC_EVENTHUB_AUTHORIZATION_RULE_ID = OptionalStringMetadataField("diagnostic_eventhub_authorization_rule_id")
    DIAGNOSTIC_EVENTHUB_NAME = OptionalStringMetadataField("diagnostic_eventhub_name")
    DIAGNOSTIC_MARKETPLACE_PARTNER_RESOURCE_ID = OptionalStringMetadataField(
        "diagnostic_marketplace_partner_resource_id"
    )
    DEFENDER_RESOURCE_TYPE = OptionalStringMetadataField("defender_resource_type")
    DEFENDER_PRICING_TIER = OptionalStringMetadataField("defender_pricing_tier")
    DEFENDER_SUBPLAN = OptionalStringMetadataField("defender_subplan")
    SECURITY_CENTER_AUTO_PROVISIONING_STATE = OptionalStringMetadataField("security_center_auto_provisioning_state")
    SECURITY_CENTER_CONTACT_EMAIL = OptionalStringMetadataField("security_center_contact_email")
    SECURITY_CENTER_CONTACT_PHONE = OptionalStringMetadataField("security_center_contact_phone")
    SECURITY_CENTER_ALERT_NOTIFICATIONS_STATE = OptionalStringMetadataField("security_center_alert_notifications_state")
    SECURITY_CENTER_ALERTS_TO_ADMINS_STATE = OptionalStringMetadataField("security_center_alerts_to_admins_state")
    SECURITY_CENTER_WORKSPACE_SCOPE = OptionalStringMetadataField("security_center_workspace_scope")
    SECURITY_CENTER_WORKSPACE_ID = OptionalStringMetadataField("security_center_workspace_id")
    SECURITY_CENTER_SETTING_NAME = OptionalStringMetadataField("security_center_setting_name")
    SECURITY_CENTER_SETTING_STATE = OptionalStringMetadataField("security_center_setting_state")
    ADVANCED_THREAT_PROTECTION_TARGET_RESOURCE_ID = OptionalStringMetadataField(
        "advanced_threat_protection_target_resource_id"
    )
    ADVANCED_THREAT_PROTECTION_STATE = OptionalStringMetadataField("advanced_threat_protection_state")
    KEY_VAULT_REFERENCE = OptionalStringMetadataField("key_vault_reference")
    RESOLVED_KEY_VAULT_ADDRESS = OptionalStringMetadataField("resolved_key_vault_address")
    KEY_VAULT_SECRET_NAME = OptionalStringMetadataField("key_vault_secret_name")
    KEY_VAULT_SECRET_URI = OptionalStringMetadataField("key_vault_secret_uri")
    KEY_VAULT_SECRET_VERSIONLESS_URI = OptionalStringMetadataField("key_vault_secret_versionless_uri")
    KEY_VAULT_SECRET_VERSION = OptionalStringMetadataField("key_vault_secret_version")
    KEY_VAULT_SECRET_RESOURCE_ID = OptionalStringMetadataField("key_vault_secret_resource_id")
    KEY_VAULT_EXPIRATION_DATE = OptionalStringMetadataField("key_vault_expiration_date")
    KEY_VAULT_NOT_BEFORE_DATE = OptionalStringMetadataField("key_vault_not_before_date")
    KEY_VAULT_KEY_TYPE = OptionalStringMetadataField("key_vault_key_type")
    KEY_VAULT_KEY_CURVE = OptionalStringMetadataField("key_vault_key_curve")
    KEY_VAULT_ROTATION_POLICY_EXPIRE_AFTER = OptionalStringMetadataField("key_vault_rotation_policy_expire_after")
    KEY_VAULT_ROTATION_POLICY_NOTIFY_BEFORE_EXPIRY = OptionalStringMetadataField(
        "key_vault_rotation_policy_notify_before_expiry"
    )
    KEY_VAULT_ROTATION_POLICY_AUTOMATIC_TIME_AFTER_CREATION = OptionalStringMetadataField(
        "key_vault_rotation_policy_automatic_time_after_creation"
    )
    KEY_VAULT_ROTATION_POLICY_AUTOMATIC_TIME_BEFORE_EXPIRY = OptionalStringMetadataField(
        "key_vault_rotation_policy_automatic_time_before_expiry"
    )
    CONTAINER_ACCESS_TYPE = OptionalStringMetadataField("container_access_type")
    STORAGE_CUSTOMER_MANAGED_KEY_ID = OptionalStringMetadataField("storage_customer_managed_key_id")
    STORAGE_CUSTOMER_MANAGED_KEY_IDENTITY_ID = OptionalStringMetadataField("storage_customer_managed_key_identity_id")
    MIN_TLS_VERSION = OptionalStringMetadataField("min_tls_version")
    FTPS_STATE = OptionalStringMetadataField("ftps_state")
    NETWORK_DEFAULT_ACTION = OptionalStringMetadataField("network_default_action")
    NETWORK_RULE_SOURCE_ADDRESS = OptionalStringMetadataField("network_rule_source_address")
    PUBLIC_NETWORK_FALLBACK_STATE = OptionalStringMetadataField("public_network_fallback_state")
    LOCATION = OptionalStringMetadataField("location")
    NETWORK_FLOW_LOG_ID = OptionalStringMetadataField("network_flow_log_id")
    NETWORK_FLOW_LOG_NAME = OptionalStringMetadataField("network_flow_log_name")
    NETWORK_FLOW_LOG_STATE = OptionalStringMetadataField("network_flow_log_state")
    NETWORK_FLOW_LOG_TARGET_RESOURCE_ID = OptionalStringMetadataField("network_flow_log_target_resource_id")
    NETWORK_FLOW_LOG_NETWORK_SECURITY_GROUP_ID = OptionalStringMetadataField(
        "network_flow_log_network_security_group_id"
    )
    NETWORK_FLOW_LOG_STORAGE_ACCOUNT_ID = OptionalStringMetadataField("network_flow_log_storage_account_id")
    NETWORK_FLOW_LOG_NETWORK_WATCHER_NAME = OptionalStringMetadataField("network_flow_log_network_watcher_name")
    NETWORK_FLOW_LOG_RESOURCE_GROUP_NAME = OptionalStringMetadataField("network_flow_log_resource_group_name")
    NETWORK_FLOW_LOG_RETENTION_STATE = OptionalStringMetadataField("network_flow_log_retention_state")
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS_STATE = OptionalStringMetadataField("network_flow_log_traffic_analytics_state")
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS_WORKSPACE_ID = OptionalStringMetadataField(
        "network_flow_log_traffic_analytics_workspace_id"
    )
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS_WORKSPACE_REGION = OptionalStringMetadataField(
        "network_flow_log_traffic_analytics_workspace_region"
    )
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS_WORKSPACE_RESOURCE_ID = OptionalStringMetadataField(
        "network_flow_log_traffic_analytics_workspace_resource_id"
    )
    LOAD_BALANCER_ID = OptionalStringMetadataField("load_balancer_id")
    LOAD_BALANCER_SKU = OptionalStringMetadataField("load_balancer_sku")
    LOAD_BALANCER_EXPOSURE_STATE = OptionalStringMetadataField("load_balancer_exposure_state")
    APPLICATION_GATEWAY_ID = OptionalStringMetadataField("application_gateway_id")
    APPLICATION_GATEWAY_SKU = OptionalStringMetadataField("application_gateway_sku")
    APPLICATION_GATEWAY_EXPOSURE_STATE = OptionalStringMetadataField("application_gateway_exposure_state")
    APPLICATION_GATEWAY_EDGE_PROTECTION_STATE = OptionalStringMetadataField("application_gateway_edge_protection_state")
    APPLICATION_GATEWAY_FIREWALL_POLICY_ID = OptionalStringMetadataField("application_gateway_firewall_policy_id")
    APPLICATION_GATEWAY_WAF_ENABLED_STATE = OptionalStringMetadataField("application_gateway_waf_enabled_state")
    APPLICATION_GATEWAY_WAF_MODE = OptionalStringMetadataField("application_gateway_waf_mode")
    APPLICATION_GATEWAY_WAF_RULE_SET_TYPE = OptionalStringMetadataField("application_gateway_waf_rule_set_type")
    APPLICATION_GATEWAY_WAF_RULE_SET_VERSION = OptionalStringMetadataField("application_gateway_waf_rule_set_version")
    VIRTUAL_NETWORK_REFERENCE = OptionalStringMetadataField("virtual_network_reference")
    RESOLVED_VIRTUAL_NETWORK_ADDRESS = OptionalStringMetadataField("resolved_virtual_network_address")
    NETWORK_SECURITY_GROUP_REFERENCE = OptionalStringMetadataField("network_security_group_reference")
    SUBNET_REFERENCE = OptionalStringMetadataField("subnet_reference")
    NETWORK_INTERFACE_REFERENCE = OptionalStringMetadataField("network_interface_reference")
    PUBLIC_IP_ADDRESS = OptionalStringMetadataField("public_ip_address")
    VM_SIZE = OptionalStringMetadataField("vm_size")
    OS_TYPE = OptionalStringMetadataField("os_type")
    TENANT_ID = OptionalStringMetadataField("tenant_id")
    OBJECT_ID = OptionalStringMetadataField("object_id")
    APPLICATION_ID = OptionalStringMetadataField("application_id")
    ROLE_ASSIGNMENT_SCOPE = OptionalStringMetadataField("role_assignment_scope")
    ROLE_DEFINITION_NAME = OptionalStringMetadataField("role_definition_name")
    ROLE_DEFINITION_ID = OptionalStringMetadataField("role_definition_id")
    ROLE_DEFINITION_SCOPE = OptionalStringMetadataField("role_definition_scope")
    ROLE_ASSIGNMENT_CONDITION = OptionalStringMetadataField("role_assignment_condition")
    PRINCIPAL_ID = OptionalStringMetadataField("principal_id")
    PRINCIPAL_TYPE = OptionalStringMetadataField("principal_type")
    RESOLVED_MANAGED_IDENTITY_ADDRESS = OptionalStringMetadataField("resolved_managed_identity_address")
    RESOLVED_ROLE_DEFINITION_ADDRESS = OptionalStringMetadataField("resolved_role_definition_address")
    ROLE_ASSIGNMENT_SCOPE_KIND = OptionalStringMetadataField("role_assignment_scope_kind")
    ROLE_ASSIGNMENT_TARGET_RESOURCE_ADDRESS = OptionalStringMetadataField("role_assignment_target_resource_address")
    ROLE_ASSIGNMENT_TARGET_RESOURCE_TYPE = OptionalStringMetadataField("role_assignment_target_resource_type")
    CLIENT_ID = OptionalStringMetadataField("client_id")
    IDENTITY_TYPE = OptionalStringMetadataField("identity_type")
    MSSQL_DATABASE_ID = OptionalStringMetadataField("mssql_database_id")
    MSSQL_SERVER_ID = OptionalStringMetadataField("mssql_server_id")
    MSSQL_FIREWALL_START_IP = OptionalStringMetadataField("mssql_firewall_start_ip")
    MSSQL_FIREWALL_END_IP = OptionalStringMetadataField("mssql_firewall_end_ip")
    MSSQL_VNET_SUBNET_ID = OptionalStringMetadataField("mssql_vnet_subnet_id")
    MSSQL_SECURITY_ALERT_STATE = OptionalStringMetadataField("mssql_security_alert_state")
    MSSQL_SHORT_TERM_RETENTION_STATE = OptionalStringMetadataField("mssql_short_term_retention_state")
    MSSQL_LONG_TERM_RETENTION_STATE = OptionalStringMetadataField("mssql_long_term_retention_state")
    MSSQL_LONG_TERM_WEEKLY_RETENTION = OptionalStringMetadataField("mssql_long_term_weekly_retention")
    MSSQL_LONG_TERM_MONTHLY_RETENTION = OptionalStringMetadataField("mssql_long_term_monthly_retention")
    MSSQL_LONG_TERM_YEARLY_RETENTION = OptionalStringMetadataField("mssql_long_term_yearly_retention")
    MSSQL_GEO_BACKUP_STATE = OptionalStringMetadataField("mssql_geo_backup_state")
    MSSQL_BACKUP_STORAGE_REDUNDANCY = OptionalStringMetadataField("mssql_backup_storage_redundancy")
    POSTGRESQL_SERVER_ID = OptionalStringMetadataField("postgresql_server_id")
    POSTGRESQL_FIREWALL_START_IP = OptionalStringMetadataField("postgresql_firewall_start_ip")
    POSTGRESQL_FIREWALL_END_IP = OptionalStringMetadataField("postgresql_firewall_end_ip")
    POSTGRESQL_SSL_MIN_PROTOCOL_VERSION = OptionalStringMetadataField("postgresql_ssl_min_protocol_version")
    POSTGRESQL_GEO_REDUNDANT_BACKUP_ENABLED = BoolMetadataField("postgresql_geo_redundant_backup_enabled")
    POSTGRESQL_DELEGATED_SUBNET_ID = OptionalStringMetadataField("postgresql_delegated_subnet_id")
    POSTGRESQL_CONFIG_NAME = OptionalStringMetadataField("postgresql_config_name")
    POSTGRESQL_CONFIG_VALUE = OptionalStringMetadataField("postgresql_config_value")
    POSTGRESQL_CONFIG_SERVER_ID = OptionalStringMetadataField("postgresql_config_server_id")
    PRIVATE_ENDPOINT_ID = OptionalStringMetadataField("private_endpoint_id")
    PRIVATE_DNS_ZONE_ID = OptionalStringMetadataField("private_dns_zone_id")
    PRIVATE_DNS_ZONE_REFERENCE = OptionalStringMetadataField("private_dns_zone_reference")
    PRIVATE_DNS_ZONE_VIRTUAL_NETWORK_LINK_ID = OptionalStringMetadataField("private_dns_zone_virtual_network_link_id")
    PRIVATE_DNS_ZONE_VIRTUAL_NETWORK_REFERENCE = OptionalStringMetadataField(
        "private_dns_zone_virtual_network_reference"
    )
    PRIVATE_DNS_ZONE_REGISTRATION_STATE = OptionalStringMetadataField("private_dns_zone_registration_state")
    PRIVATE_DNS_ZONE_GROUP_STATE = OptionalStringMetadataField("private_dns_zone_group_state")
    PRIVATE_DNS_ZONE_IDS_STATE = OptionalStringMetadataField("private_dns_zone_ids_state")

    ALLOW_NESTED_ITEMS_TO_BE_PUBLIC = BoolMetadataField("allow_nested_items_to_be_public")
    SHARED_ACCESS_KEY_ENABLED = BoolMetadataField("shared_access_key_enabled")
    STORAGE_INFRASTRUCTURE_ENCRYPTION_ENABLED = BoolMetadataField("storage_infrastructure_encryption_enabled")
    STORAGE_BLOB_VERSIONING_ENABLED = BoolMetadataField("storage_blob_versioning_enabled")
    PUBLIC_NETWORK_ACCESS_ENABLED = BoolMetadataField("public_network_access_enabled")
    DEFAULT_OUTBOUND_ACCESS_ENABLED = BoolMetadataField("default_outbound_access_enabled", default=True)
    IP_FORWARDING_ENABLED = BoolMetadataField("ip_forwarding_enabled")
    PURGE_PROTECTION_ENABLED = BoolMetadataField("purge_protection_enabled")
    RBAC_AUTHORIZATION_ENABLED = BoolMetadataField("rbac_authorization_enabled")
    CUSTOM_ROLE_DEFINITION = BoolMetadataField("custom_role_definition")

    PUBLIC_CONTAINER_ADDRESSES = StringListMetadataField("public_container_addresses")
    UNRESOLVED_STORAGE_ACCOUNT_REFERENCES = StringListMetadataField("unresolved_storage_account_references")
    STORAGE_POSTURE_UNCERTAINTIES = StringListMetadataField("storage_posture_uncertainties")
    SERVICE_BUS_POSTURE_UNCERTAINTIES = StringListMetadataField("service_bus_posture_uncertainties")
    UNRESOLVED_SERVICE_BUS_NAMESPACE_REFERENCES = StringListMetadataField("unresolved_service_bus_namespace_references")
    CONTAINER_REGISTRY_POSTURE_UNCERTAINTIES = StringListMetadataField("container_registry_posture_uncertainties")
    CONTAINER_REGISTRY_RETENTION_DAYS = OptionalIntMetadataField("container_registry_retention_days")
    STORAGE_BLOB_DELETE_RETENTION_DAYS = OptionalIntMetadataField("storage_blob_delete_retention_days")
    STORAGE_CONTAINER_DELETE_RETENTION_DAYS = OptionalIntMetadataField("storage_container_delete_retention_days")
    STORAGE_BLOB_RESTORE_POLICY_DAYS = OptionalIntMetadataField("storage_blob_restore_policy_days")
    NETWORK_FLOW_LOG_VERSION = OptionalIntMetadataField("network_flow_log_version")
    NETWORK_FLOW_LOG_RETENTION_DAYS = OptionalIntMetadataField("network_flow_log_retention_days")
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS_INTERVAL_MINUTES = OptionalIntMetadataField(
        "network_flow_log_traffic_analytics_interval_minutes"
    )
    NETWORK_TELEMETRY_POSTURE_UNCERTAINTIES = StringListMetadataField("network_telemetry_posture_uncertainties")
    APP_SERVICE_POSTURE_UNCERTAINTIES = StringListMetadataField("app_service_posture_uncertainties")
    APP_SERVICE_AUTH_POSTURE_UNCERTAINTIES = StringListMetadataField("app_service_auth_posture_uncertainties")
    APP_SERVICE_SECRET_POSTURE_UNCERTAINTIES = StringListMetadataField("app_service_secret_posture_uncertainties")
    APP_SERVICE_KEY_VAULT_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField(
        "app_service_key_vault_access_path_uncertainties"
    )
    APP_SERVICE_STORAGE_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField(
        "app_service_storage_access_path_uncertainties"
    )
    APP_SERVICE_ACCESS_RESTRICTIONS = DictListMetadataField("app_service_access_restrictions")
    APP_SERVICE_SCM_ACCESS_RESTRICTIONS = DictListMetadataField("app_service_scm_access_restrictions")
    APP_SERVICE_SECRET_REFERENCES = DictListMetadataField("app_service_secret_references")
    APP_SERVICE_KEY_VAULT_ACCESS_PATHS = DictListMetadataField("app_service_key_vault_access_paths")
    APP_SERVICE_STORAGE_ACCESS_PATHS = DictListMetadataField("app_service_storage_access_paths")
    APP_SERVICE_AUTH_SETTINGS = DictMetadataField("app_service_auth_settings")
    APP_SERVICE_AUTH_SETTINGS_V2 = DictMetadataField("app_service_auth_settings_v2")
    CONTAINER_IMAGE_REFERENCES = DictListMetadataField("container_image_references")
    CONTAINER_IMAGE_POSTURE_UNCERTAINTIES = StringListMetadataField("container_image_posture_uncertainties")
    ACR_WRITE_PATH_UNCERTAINTIES = StringListMetadataField("acr_write_path_uncertainties")
    AKS_AUTHORIZED_IP_RANGES = StringListMetadataField("aks_authorized_ip_ranges")
    AKS_AAD_ADMIN_GROUP_OBJECT_IDS = StringListMetadataField("aks_aad_admin_group_object_ids")
    AKS_USER_ASSIGNED_IDENTITY_IDS = StringListMetadataField("aks_user_assigned_identity_ids")
    AKS_POSTURE_UNCERTAINTIES = StringListMetadataField("aks_posture_uncertainties")
    DIAGNOSTIC_ENABLED_LOG_CATEGORIES = StringListMetadataField("diagnostic_enabled_log_categories")
    DIAGNOSTIC_ENABLED_LOG_CATEGORY_GROUPS = StringListMetadataField("diagnostic_enabled_log_category_groups")
    DIAGNOSTIC_METRIC_CATEGORIES = StringListMetadataField("diagnostic_metric_categories")
    DEFENDER_EXTENSION_NAMES = StringListMetadataField("defender_extension_names")
    AZURE_SECURITY_POSTURE_UNCERTAINTIES = StringListMetadataField("azure_security_posture_uncertainties")
    KEY_VAULT_RELATED_RESOURCE_ADDRESSES = StringListMetadataField("key_vault_related_resource_addresses")
    KEY_VAULT_NETWORK_IP_RULES = StringListMetadataField("key_vault_network_ip_rules")
    KEY_VAULT_NETWORK_SUBNET_IDS = StringListMetadataField("key_vault_network_subnet_ids")
    KEY_VAULT_NETWORK_UNCERTAINTIES = StringListMetadataField("key_vault_network_uncertainties")
    KEY_VAULT_AUTHORIZATION_UNCERTAINTIES = StringListMetadataField("key_vault_authorization_uncertainties")
    KEY_VAULT_RECOVERY_UNCERTAINTIES = StringListMetadataField("key_vault_recovery_uncertainties")
    KEY_VAULT_LIFECYCLE_UNCERTAINTIES = StringListMetadataField("key_vault_lifecycle_uncertainties")
    KEY_VAULT_IDENTITY_UNCERTAINTIES = StringListMetadataField("key_vault_identity_uncertainties")
    KEY_VAULT_CERTIFICATE_VALIDITY_MONTHS = OptionalIntMetadataField("key_vault_certificate_validity_months")
    KEY_VAULT_KEY_SIZE = OptionalIntMetadataField("key_vault_key_size")
    KEY_VAULT_KEY_OPS = StringListMetadataField("key_vault_key_ops")
    KEY_VAULT_KEY_POSTURE_UNCERTAINTIES = StringListMetadataField("key_vault_key_posture_uncertainties")
    ATTACHED_IDENTITY_REFERENCES = StringListMetadataField("attached_identity_references")
    IAM_ASSIGNMENT_POSTURE_UNCERTAINTIES = StringListMetadataField("iam_assignment_posture_uncertainties")
    MANAGED_IDENTITY_UNCERTAINTIES = StringListMetadataField("managed_identity_uncertainties")
    FEDERATED_IDENTITY_CREDENTIAL_ISSUER = OptionalStringMetadataField("federated_identity_credential_issuer")
    FEDERATED_IDENTITY_CREDENTIAL_SUBJECT = OptionalStringMetadataField("federated_identity_credential_subject")
    FEDERATED_IDENTITY_CREDENTIAL_PARENT_ID = OptionalStringMetadataField("federated_identity_credential_parent_id")
    FEDERATED_IDENTITY_CREDENTIAL_AUDIENCES = StringListMetadataField("federated_identity_credential_audiences")
    FEDERATED_IDENTITY_CREDENTIAL_UNCERTAINTIES = StringListMetadataField("federated_identity_credential_uncertainties")
    FEDERATED_MANAGED_IDENTITY_TRUST_PATH_UNCERTAINTIES = StringListMetadataField(
        "federated_managed_identity_trust_path_uncertainties"
    )
    ROLE_ASSIGNMENT_BREADTH_SIGNALS = StringListMetadataField("role_assignment_breadth_signals")
    ROLE_ASSIGNMENT_BREADTH_MITIGATIONS = StringListMetadataField("role_assignment_breadth_mitigations")
    ROLE_DEFINITION_ASSIGNABLE_SCOPES = StringListMetadataField("role_definition_assignable_scopes")
    ROLE_DEFINITION_ACTIONS = StringListMetadataField("role_definition_actions")
    ROLE_DEFINITION_NOT_ACTIONS = StringListMetadataField("role_definition_not_actions")
    ROLE_DEFINITION_DATA_ACTIONS = StringListMetadataField("role_definition_data_actions")
    ROLE_DEFINITION_NOT_DATA_ACTIONS = StringListMetadataField("role_definition_not_data_actions")
    ROLE_DEFINITION_BREADTH_SIGNALS = StringListMetadataField("role_definition_breadth_signals")
    ROLE_DEFINITION_BREADTH_MITIGATIONS = StringListMetadataField("role_definition_breadth_mitigations")
    ROLE_DEFINITION_UNCERTAINTIES = StringListMetadataField("role_definition_uncertainties")
    MSSQL_SHORT_TERM_RETENTION_DAYS = OptionalIntMetadataField("mssql_short_term_retention_days")
    MSSQL_BACKUP_INTERVAL_HOURS = OptionalIntMetadataField("mssql_backup_interval_hours")
    MSSQL_LONG_TERM_WEEK_OF_YEAR = OptionalIntMetadataField("mssql_long_term_week_of_year")
    MSSQL_POSTURE_UNCERTAINTIES = StringListMetadataField("mssql_posture_uncertainties")
    MSSQL_FIREWALL_RULE_ADDRESSES = StringListMetadataField("mssql_firewall_rule_addresses")
    MSSQL_VNET_RULE_ADDRESSES = StringListMetadataField("mssql_vnet_rule_addresses")
    POSTGRESQL_POSTURE_UNCERTAINTIES = StringListMetadataField("postgresql_posture_uncertainties")
    PRIVATE_CONNECTION_RESOURCE_IDS = StringListMetadataField("private_connection_resource_ids")
    PRIVATE_ENDPOINT_SUBRESOURCE_NAMES = StringListMetadataField("private_endpoint_subresource_names")
    PRIVATE_DNS_ZONE_GROUP_NAMES = StringListMetadataField("private_dns_zone_group_names")
    PRIVATE_DNS_ZONE_IDS = StringListMetadataField("private_dns_zone_ids")
    PRIVATE_ENDPOINT_UNCERTAINTIES = StringListMetadataField("private_endpoint_uncertainties")
    PRIVATE_DNS_ZONE_UNCERTAINTIES = StringListMetadataField("private_dns_zone_uncertainties")
    ADDRESS_SPACE = StringListMetadataField("address_space")
    ADDRESS_PREFIXES = StringListMetadataField("address_prefixes")
    NETWORK_INTERFACE_REFERENCES = StringListMetadataField("network_interface_references")
    PUBLIC_IP_REFERENCES = StringListMetadataField("public_ip_references")
    LOAD_BALANCER_PUBLIC_IP_REFERENCES = StringListMetadataField("load_balancer_public_ip_references")
    LOAD_BALANCER_PUBLIC_IP_PREFIX_REFERENCES = StringListMetadataField("load_balancer_public_ip_prefix_references")
    LOAD_BALANCER_SUBNET_REFERENCES = StringListMetadataField("load_balancer_subnet_references")
    LOAD_BALANCER_PRIVATE_IP_ADDRESSES = StringListMetadataField("load_balancer_private_ip_addresses")
    LOAD_BALANCER_POSTURE_UNCERTAINTIES = StringListMetadataField("load_balancer_posture_uncertainties")
    APPLICATION_GATEWAY_PUBLIC_IP_REFERENCES = StringListMetadataField("application_gateway_public_ip_references")
    APPLICATION_GATEWAY_SUBNET_REFERENCES = StringListMetadataField("application_gateway_subnet_references")
    APPLICATION_GATEWAY_PRIVATE_IP_ADDRESSES = StringListMetadataField("application_gateway_private_ip_addresses")
    APPLICATION_GATEWAY_POSTURE_UNCERTAINTIES = StringListMetadataField("application_gateway_posture_uncertainties")
    APPLICATION_GATEWAY_EDGE_PROTECTION_UNCERTAINTIES = StringListMetadataField(
        "application_gateway_edge_protection_uncertainties"
    )
    RESOLVED_SUBNET_ADDRESSES = StringListMetadataField("resolved_subnet_addresses")
    RESOLVED_NETWORK_SECURITY_GROUP_ADDRESSES = StringListMetadataField("resolved_network_security_group_addresses")
    RESOLVED_NETWORK_INTERFACE_ADDRESSES = StringListMetadataField("resolved_network_interface_addresses")
    RESOLVED_PUBLIC_IP_ADDRESSES = StringListMetadataField("resolved_public_ip_addresses")
    ASSOCIATED_RESOURCE_ADDRESSES = StringListMetadataField("associated_resource_addresses")
    STANDALONE_RULE_ADDRESSES = StringListMetadataField("standalone_rule_addresses")
    UNRESOLVED_RESOURCE_REFERENCES = StringListMetadataField("unresolved_resource_references")

    IP_CONFIGURATIONS = DictListMetadataField("ip_configurations")
    LOAD_BALANCER_FRONTENDS = DictListMetadataField("load_balancer_frontends")
    APPLICATION_GATEWAY_FRONTENDS = DictListMetadataField("application_gateway_frontends")
    APPLICATION_GATEWAY_HTTP_LISTENERS = DictListMetadataField("application_gateway_http_listeners")
    APPLICATION_GATEWAY_ROUTING_RULES = DictListMetadataField("application_gateway_routing_rules")
    APPLICATION_GATEWAY_WAF_CONFIGURATIONS = DictListMetadataField("application_gateway_waf_configurations")
    NETWORK_SECURITY_RULES = DictListMetadataField("network_security_rules")
    NETWORK_FLOW_LOG_RETENTION_POLICY = DictMetadataField("network_flow_log_retention_policy")
    NETWORK_FLOW_LOG_TRAFFIC_ANALYTICS = DictMetadataField("network_flow_log_traffic_analytics")
    PUBLIC_COMPUTE_EXPOSURE_PATHS = DictListMetadataField("public_compute_exposure_paths")
    KEY_VAULT_ACCESS_POLICIES = DictListMetadataField("key_vault_access_policies")
    KEY_VAULT_ROLE_ASSIGNMENTS = DictListMetadataField("key_vault_role_assignments")
    KEY_VAULT_ROTATION_POLICY = DictMetadataField("key_vault_rotation_policy")
    MANAGED_IDENTITY_ROLE_ASSIGNMENTS = DictListMetadataField("managed_identity_role_assignments")
    FEDERATED_MANAGED_IDENTITY_TRUST_PATHS = DictListMetadataField("federated_managed_identity_trust_paths")
    ACR_WRITE_PATHS = DictListMetadataField("acr_write_paths")
    PRIVILEGED_ACCESS_GRANTS = DictListMetadataField("privileged_access_grants")
    ROLE_DEFINITION_PERMISSIONS = DictListMetadataField("role_definition_permissions")
    PRIVATE_SERVICE_CONNECTIONS = DictListMetadataField("private_service_connections")
    PRIVATE_DNS_ZONE_GROUPS = DictListMetadataField("private_dns_zone_groups")
    AKS_KUBELET_IDENTITIES = DictListMetadataField("aks_kubelet_identities")
    AKS_MAINTENANCE_WINDOWS = DictListMetadataField("aks_maintenance_windows")
    DIAGNOSTIC_LOG_RECORDS = DictListMetadataField("diagnostic_log_records")
    DIAGNOSTIC_METRIC_RECORDS = DictListMetadataField("diagnostic_metric_records")
    DEFENDER_EXTENSIONS = DictListMetadataField("defender_extensions")
    CONTAINER_REGISTRY_NETWORK_RULE_SET = DictMetadataField("container_registry_network_rule_set")
    CONTAINER_REGISTRY_ENCRYPTION_CONFIGURATION = DictMetadataField("container_registry_encryption_configuration")
