from __future__ import annotations

from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Protocol

from fastapi import Request, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse
from starlette.types import ASGIApp, Message, Receive, Scope, Send

from apps.dashboard.view_models import DashboardAnalysis, _base_context, _sanitize_dashboard_payload
from tfstride.app import TfStride
from tfstride.input.terraform_plan import TerraformPlanLoadError
from tfstride.reporting.json_report import build_json_report_payload
from tfstride.reporting.markdown import render_markdown

MAX_UPLOAD_BYTES = 10 * 1024 * 1024
MAX_MULTIPART_ENVELOPE_BYTES = 1024 * 1024
MAX_MULTIPART_REQUEST_BYTES = MAX_UPLOAD_BYTES + MAX_MULTIPART_ENVELOPE_BYTES
UPLOAD_READ_CHUNK_BYTES = 1024 * 1024
UPLOAD_ENDPOINT_PATHS = frozenset({"/analyze", "/api/analyze"})
DEFAULT_REPORT_TITLE = "tfSTRIDE Report"
EMPTY_UPLOAD_MESSAGE = "Upload a non-empty Terraform plan JSON file."
INVALID_PLAN_UPLOAD_MESSAGE = "Upload a valid Terraform plan JSON file generated by `terraform show -json tfplan`."


class TemplateResponder(Protocol):
    def __call__(
        self,
        request: Request,
        template_name: str,
        context: dict[str, object],
        *,
        status_code: int = 200,
    ) -> HTMLResponse: ...


class DashboardInputError(ValueError):
    """Raised when an uploaded plan cannot be analyzed by the dashboard."""

    def __init__(self, public_message: str) -> None:
        super().__init__("dashboard input error")
        self.public_message = public_message


class _UploadTooLarge(ValueError):
    """Raised when a dashboard upload exceeds the request body size limit."""


class UploadSizeLimitMiddleware:
    def __init__(self, app: ASGIApp, *, template_response: TemplateResponder) -> None:
        self.app = app
        self.template_response = template_response

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http" or scope.get("method") != "POST" or scope.get("path") not in UPLOAD_ENDPOINT_PATHS:
            await self.app(scope, receive, send)
            return

        bytes_seen = 0

        # Enforce a hard ceiling on the multipart body before Starlette finishes
        # parsing the upload into an UploadFile object.
        async def limited_receive() -> Message:
            nonlocal bytes_seen
            message = await receive()
            if message["type"] != "http.request":
                return message

            body = message.get("body", b"")
            bytes_seen += len(body)
            if bytes_seen > MAX_MULTIPART_REQUEST_BYTES:
                raise _UploadTooLarge
            return message

        try:
            await self.app(scope, limited_receive, send)
        except _UploadTooLarge:
            response = _upload_limit_response(scope, receive, self.template_response)
            await response(scope, receive, send)


async def analyze_upload(
    upload: UploadFile,
    *,
    title: str,
    engine: TfStride,
) -> DashboardAnalysis:
    filename = Path(upload.filename or "uploaded-plan.json").name or "uploaded-plan.json"
    bytes_written = 0

    with TemporaryDirectory(prefix="tfstride-dashboard-") as tmp_dir:
        plan_path = Path(tmp_dir) / filename
        try:
            with plan_path.open("wb") as plan_file:
                while True:
                    chunk = await upload.read(UPLOAD_READ_CHUNK_BYTES)
                    if not chunk:
                        break
                    if bytes_written + len(chunk) > MAX_UPLOAD_BYTES:
                        raise DashboardInputError(_upload_too_large_message())
                    plan_file.write(chunk)
                    bytes_written += len(chunk)
        finally:
            await upload.close()

        if bytes_written == 0:
            raise DashboardInputError(EMPTY_UPLOAD_MESSAGE)

        return analyze_plan_path(plan_path, title=title or DEFAULT_REPORT_TITLE, engine=engine)


def analyze_plan_path(
    plan_path: Path,
    *,
    title: str,
    engine: TfStride,
) -> DashboardAnalysis:
    result = engine.analyze_plan(plan_path, title=title)
    payload = _sanitize_dashboard_payload(build_json_report_payload(result))
    markdown_report = render_markdown(result)
    return DashboardAnalysis(payload=payload, markdown_report=markdown_report)


def public_dashboard_error_message(exc: DashboardInputError | TerraformPlanLoadError) -> str:
    if isinstance(exc, DashboardInputError):
        return exc.public_message
    return INVALID_PLAN_UPLOAD_MESSAGE


def _upload_too_large_message() -> str:
    return f"Uploaded plan exceeds the {MAX_UPLOAD_BYTES // (1024 * 1024)} MiB dashboard limit."


def _upload_limit_response(
    scope: Scope,
    receive: Receive,
    template_response: TemplateResponder,
) -> HTMLResponse | JSONResponse:
    message = _upload_too_large_message()
    if scope.get("path") == "/api/analyze":
        return JSONResponse(
            status_code=413,
            content={
                "kind": "tfstride-error",
                "message": message,
            },
        )

    request = Request(scope, receive)
    return template_response(
        request,
        "index.html",
        _base_context(request, max_upload_bytes=MAX_UPLOAD_BYTES, error=message),
        status_code=413,
    )
