from __future__ import annotations

from tfstride.providers.aws.account_identity_evidence import AwsAccountArnInput
from tfstride.providers.aws.audit_telemetry_disruption_evidence import (
    AwsEcsCloudTrailAuditTelemetryDisruptionPath,
)
from tfstride.providers.aws.kms_dependency_evidence import AwsKmsEncryptionDependency
from tfstride.providers.aws.kms_evidence import (
    AwsEcsKmsManagementPath,
    AwsEcsKmsOperationPath,
    AwsKmsAliasRelationship,
    AwsKmsGrantRelationship,
    AwsKmsKeyPolicyEvidence,
    AwsKmsOperationAuthorization,
)
from tfstride.providers.aws.message_removal_evidence import AwsEcsSqsMessageRemovalPath
from tfstride.providers.aws.messaging_topology_destruction_evidence import (
    AwsEcsMessagingTopologyDestructionPath,
)
from tfstride.providers.aws.object_storage_deletion_evidence import AwsEcsS3ObjectDeletionPath
from tfstride.providers.aws.object_storage_topology_destruction_evidence import (
    AwsEcsS3BucketTopologyDestructionPath,
)
from tfstride.providers.aws.protected_data_evidence import (
    AwsEcsS3AccessPath,
    AwsEcsS3ProtectedDataConvergence,
)
from tfstride.providers.aws.secret_management_evidence import (
    AwsEcsSecretsManagerManagementPath,
    AwsSecretsManagerOperationAuthorization,
)
from tfstride.providers.aws.structured_data_deletion_evidence import (
    AwsEcsDynamoDbItemDeletionPath,
)
from tfstride.providers.aws.structured_data_topology_destruction_evidence import (
    AwsEcsDynamoDbTableTopologyDestructionPath,
)
from tfstride.resource_metadata import (
    BoolDictMetadataField,
    BoolMetadataField,
    DictListMetadataField,
    DictMetadataField,
    OptionalIntMetadataField,
    OptionalStringMetadataField,
    RecordListMetadataField,
    ResourceMetadata,
    StringListMetadataField,
)

AWS_SHARED_CORE_METADATA_FIELD_NAMES = frozenset(
    {
        "PUBLIC_ACCESS_CONFIGURED",
        "PUBLIC_ACCESS_REASONS",
        "PUBLIC_EXPOSURE_REASONS",
    }
)


class AwsResourceMetadata:
    """AWS-owned metadata fields plus shared core fields used by AWS decorators."""

    INTERNET_INGRESS = BoolMetadataField("internet_ingress")
    FRONTED_BY_INTERNET_FACING_LOAD_BALANCER = BoolMetadataField("fronted_by_internet_facing_load_balancer")
    MAP_PUBLIC_IP_ON_LAUNCH = BoolMetadataField("map_public_ip_on_launch")
    BLOCK_PUBLIC_ACLS = BoolMetadataField("block_public_acls")
    BLOCK_PUBLIC_POLICY = BoolMetadataField("block_public_policy")
    IGNORE_PUBLIC_ACLS = BoolMetadataField("ignore_public_acls")
    RESTRICT_PUBLIC_BUCKETS = BoolMetadataField("restrict_public_buckets")

    ROUTE_TABLE_IDS = StringListMetadataField("route_table_ids")
    INTERNET_FACING_LOAD_BALANCER_ADDRESSES = StringListMetadataField("internet_facing_load_balancer_addresses")
    ROLE_REFERENCES = StringListMetadataField("role_references")
    RESOLVED_ROLE_REFERENCES = StringListMetadataField("resolved_role_references")
    RESOLVED_ROLE_ADDRESSES = StringListMetadataField("resolved_role_addresses")
    STANDALONE_RULE_ADDRESSES = StringListMetadataField("standalone_rule_addresses")
    INLINE_POLICY_RESOURCE_ADDRESSES = StringListMetadataField("inline_policy_resource_addresses")
    INLINE_POLICY_NAMES = StringListMetadataField("inline_policy_names")
    IAM_POLICY_COMPLETENESS_STATE = OptionalStringMetadataField("iam_policy_completeness_state")
    IAM_POLICY_POSTURE_UNCERTAINTIES = StringListMetadataField("iam_policy_posture_uncertainties")
    IAM_PERMISSIONS_BOUNDARY_ARN = OptionalStringMetadataField("iam_permissions_boundary_arn")
    IAM_PERMISSIONS_BOUNDARY_STATE = OptionalStringMetadataField("iam_permissions_boundary_state")
    IAM_PERMISSIONS_BOUNDARY_UNCERTAINTIES = StringListMetadataField("iam_permissions_boundary_uncertainties")
    UNRESOLVED_ATTACHED_POLICY_ARNS = StringListMetadataField("unresolved_attached_policy_arns")
    ATTACHED_POLICY_ARNS = StringListMetadataField("attached_policy_arns")
    ATTACHED_POLICY_ADDRESSES = StringListMetadataField("attached_policy_addresses")
    UNRESOLVED_ROLE_REFERENCES = StringListMetadataField("unresolved_role_references")
    UNRESOLVED_INSTANCE_PROFILES = StringListMetadataField("unresolved_instance_profiles")
    RESOLVED_INSTANCE_PROFILE_ADDRESSES = StringListMetadataField("resolved_instance_profile_addresses")
    UNRESOLVED_CLUSTER_REFERENCES = StringListMetadataField("unresolved_cluster_references")
    RESOLVED_CLUSTER_ADDRESSES = StringListMetadataField("resolved_cluster_addresses")
    UNRESOLVED_TASK_DEFINITION_REFERENCES = StringListMetadataField("unresolved_task_definition_references")
    RESOLVED_TASK_DEFINITION_ADDRESSES = StringListMetadataField("resolved_task_definition_addresses")
    RESOLVED_TASK_ROLE_ADDRESSES = StringListMetadataField("resolved_task_role_addresses")
    UNRESOLVED_TASK_ROLE_ARNS = StringListMetadataField("unresolved_task_role_arns")
    RESOLVED_EXECUTION_ROLE_ADDRESSES = StringListMetadataField("resolved_execution_role_addresses")
    UNRESOLVED_EXECUTION_ROLE_ARNS = StringListMetadataField("unresolved_execution_role_arns")
    UNRESOLVED_BUCKET_REFERENCES = StringListMetadataField("unresolved_bucket_references")
    UNRESOLVED_SQS_QUEUE_REFERENCES = StringListMetadataField("unresolved_sqs_queue_references")
    SNS_POSTURE_UNCERTAINTIES = StringListMetadataField("sns_posture_uncertainties")
    SNS_TOPIC_POLICY_UNCERTAINTIES = StringListMetadataField("sns_topic_policy_uncertainties")
    SQS_POSTURE_UNCERTAINTIES = StringListMetadataField("sqs_posture_uncertainties")
    SQS_QUEUE_POLICY_UNCERTAINTIES = StringListMetadataField("sqs_queue_policy_uncertainties")
    ECR_POSTURE_UNCERTAINTIES = StringListMetadataField("ecr_posture_uncertainties")
    ECR_WRITE_PATH_UNCERTAINTIES = StringListMetadataField("ecr_write_path_uncertainties")
    ECS_SECRET_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField("ecs_secret_access_path_uncertainties")
    ECS_SECRET_MANAGEMENT_PATH_UNCERTAINTIES = StringListMetadataField("ecs_secret_management_path_uncertainties")
    ECS_S3_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField("ecs_s3_access_path_uncertainties")
    ECS_S3_OBJECT_DELETION_PATH_UNCERTAINTIES = StringListMetadataField("ecs_s3_object_deletion_path_uncertainties")
    ECS_S3_BUCKET_TOPOLOGY_DESTRUCTION_PATH_UNCERTAINTIES = StringListMetadataField(
        "ecs_s3_bucket_topology_destruction_path_uncertainties"
    )
    ECS_S3_PROTECTED_DATA_CONVERGENCE_UNCERTAINTIES = StringListMetadataField(
        "ecs_s3_protected_data_convergence_uncertainties"
    )
    ECS_MESSAGING_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField("ecs_messaging_access_path_uncertainties")
    ECS_SQS_MESSAGE_REMOVAL_PATH_UNCERTAINTIES = StringListMetadataField("ecs_sqs_message_removal_path_uncertainties")
    ECS_MESSAGING_TOPOLOGY_DESTRUCTION_PATH_UNCERTAINTIES = StringListMetadataField(
        "ecs_messaging_topology_destruction_path_uncertainties"
    )
    ECS_DYNAMODB_ACCESS_PATH_UNCERTAINTIES = StringListMetadataField("ecs_dynamodb_access_path_uncertainties")
    ECS_DYNAMODB_ITEM_DELETION_PATH_UNCERTAINTIES = StringListMetadataField(
        "ecs_dynamodb_item_deletion_path_uncertainties"
    )
    ECS_DYNAMODB_TABLE_TOPOLOGY_DESTRUCTION_PATH_UNCERTAINTIES = StringListMetadataField(
        "ecs_dynamodb_table_topology_destruction_path_uncertainties"
    )
    ECS_CLOUDTRAIL_AUDIT_TELEMETRY_DISRUPTION_PATH_UNCERTAINTIES = StringListMetadataField(
        "ecs_cloudtrail_audit_telemetry_disruption_path_uncertainties"
    )
    ECS_KMS_OPERATION_PATH_UNCERTAINTIES = StringListMetadataField("ecs_kms_operation_path_uncertainties")
    ECS_KMS_MANAGEMENT_PATH_UNCERTAINTIES = StringListMetadataField("ecs_kms_management_path_uncertainties")
    S3_POSTURE_UNCERTAINTIES = StringListMetadataField("s3_posture_uncertainties")
    S3_BUCKET_POLICY_STATE = OptionalStringMetadataField("s3_bucket_policy_state")
    S3_BUCKET_POLICY_COMPLETENESS_STATE = OptionalStringMetadataField("s3_bucket_policy_completeness_state")
    S3_BUCKET_POLICY_UNCERTAINTIES = StringListMetadataField("s3_bucket_policy_uncertainties")
    DYNAMODB_POSTURE_UNCERTAINTIES = StringListMetadataField("dynamodb_posture_uncertainties")
    DYNAMODB_INDEX_NAMES = StringListMetadataField("dynamodb_index_names")
    DYNAMODB_INDEX_INVENTORY_STATE = OptionalStringMetadataField("dynamodb_index_inventory_state")
    RDS_POSTURE_UNCERTAINTIES = StringListMetadataField("rds_posture_uncertainties")
    RDS_ENABLED_CLOUDWATCH_LOGS_EXPORTS = StringListMetadataField("rds_enabled_cloudwatch_logs_exports")
    KMS_POSTURE_UNCERTAINTIES = StringListMetadataField("kms_posture_uncertainties")
    EKS_PUBLIC_ACCESS_CIDRS = StringListMetadataField("eks_public_access_cidrs")
    EKS_SUBNET_IDS = StringListMetadataField("eks_subnet_ids")
    EKS_SECURITY_GROUP_IDS = StringListMetadataField("eks_security_group_ids")
    EKS_ENABLED_CLUSTER_LOG_TYPES = StringListMetadataField("eks_enabled_cluster_log_types")
    EKS_ENCRYPTION_RESOURCES = StringListMetadataField("eks_encryption_resources")
    EKS_ADDON_CONFIGURATION_KEYS = StringListMetadataField("eks_addon_configuration_keys")
    EKS_POSTURE_UNCERTAINTIES = StringListMetadataField("eks_posture_uncertainties")
    VPC_ENDPOINT_ROUTE_TABLE_IDS = StringListMetadataField("vpc_endpoint_route_table_ids")
    VPC_ENDPOINT_SUBNET_IDS = StringListMetadataField("vpc_endpoint_subnet_ids")
    VPC_ENDPOINT_SECURITY_GROUP_IDS = StringListMetadataField("vpc_endpoint_security_group_ids")
    VPC_ENDPOINT_DNS_NAMES = StringListMetadataField("vpc_endpoint_dns_names")
    VPC_ENDPOINT_POSTURE_UNCERTAINTIES = StringListMetadataField("vpc_endpoint_posture_uncertainties")
    FLOW_LOG_POSTURE_UNCERTAINTIES = StringListMetadataField("flow_log_posture_uncertainties")
    LAMBDA_FUNCTION_URL_CORS_ALLOW_HEADERS = StringListMetadataField("lambda_function_url_cors_allow_headers")
    LAMBDA_FUNCTION_URL_CORS_ALLOW_METHODS = StringListMetadataField("lambda_function_url_cors_allow_methods")
    LAMBDA_FUNCTION_URL_CORS_ALLOW_ORIGINS = StringListMetadataField("lambda_function_url_cors_allow_origins")
    LAMBDA_FUNCTION_URL_CORS_EXPOSE_HEADERS = StringListMetadataField("lambda_function_url_cors_expose_headers")
    LAMBDA_FUNCTION_URL_POSTURE_UNCERTAINTIES = StringListMetadataField("lambda_function_url_posture_uncertainties")
    API_GATEWAY_ENDPOINT_TYPES = StringListMetadataField("api_gateway_endpoint_types")
    API_GATEWAY_VPC_ENDPOINT_IDS = StringListMetadataField("api_gateway_vpc_endpoint_ids")
    API_GATEWAY_AUTHORIZATION_SCOPES = StringListMetadataField("api_gateway_authorization_scopes")
    API_GATEWAY_AUTHORIZER_PROVIDER_ARNS = StringListMetadataField("api_gateway_authorizer_provider_arns")
    UNRESOLVED_API_GATEWAY_API_IDS = StringListMetadataField("unresolved_api_gateway_api_ids")
    API_GATEWAY_POSTURE_UNCERTAINTIES = StringListMetadataField("api_gateway_posture_uncertainties")
    LOAD_BALANCER_LISTENER_TLS_UNCERTAINTIES = StringListMetadataField("load_balancer_listener_tls_uncertainties")
    CLOUDFRONT_ALIASES = StringListMetadataField("cloudfront_aliases")
    CLOUDFRONT_ORIGIN_IDS = StringListMetadataField("cloudfront_origin_ids")
    CLOUDFRONT_ORIGIN_DOMAIN_NAMES = StringListMetadataField("cloudfront_origin_domain_names")
    CLOUDFRONT_DEFAULT_ALLOWED_METHODS = StringListMetadataField("cloudfront_default_allowed_methods")
    CLOUDFRONT_DEFAULT_CACHED_METHODS = StringListMetadataField("cloudfront_default_cached_methods")
    CLOUDFRONT_ORDERED_VIEWER_PROTOCOL_POLICIES = StringListMetadataField("cloudfront_ordered_viewer_protocol_policies")
    CLOUDFRONT_POSTURE_UNCERTAINTIES = StringListMetadataField("cloudfront_posture_uncertainties")
    WEB_ACL_RULE_NAMES = StringListMetadataField("web_acl_rule_names")
    EDGE_PROTECTION_POSTURE_UNCERTAINTIES = StringListMetadataField("edge_protection_posture_uncertainties")
    AUDIT_DETECTION_POSTURE_UNCERTAINTIES = StringListMetadataField("audit_detection_posture_uncertainties")
    IAM_ASSIGNMENT_POSTURE_UNCERTAINTIES = StringListMetadataField("iam_assignment_posture_uncertainties")
    CALLER_IDENTITY_POSTURE_UNCERTAINTIES = StringListMetadataField("caller_identity_posture_uncertainties")
    OIDC_PROVIDER_CLIENT_IDS = StringListMetadataField("oidc_provider_client_ids")
    OIDC_PROVIDER_THUMBPRINTS = StringListMetadataField("oidc_provider_thumbprints")
    OIDC_PROVIDER_POSTURE_UNCERTAINTIES = StringListMetadataField("oidc_provider_posture_uncertainties")
    CLOUDTRAIL_INSIGHT_SELECTORS = StringListMetadataField("cloudtrail_insight_selectors")
    CONFIG_RECORDER_RESOURCE_TYPES = StringListMetadataField("config_recorder_resource_types")
    UNRESOLVED_SECRET_ARNS = StringListMetadataField("unresolved_secret_arns")
    UNRESOLVED_SECRET_REFERENCES = StringListMetadataField("unresolved_secret_references")
    SECRETS_MANAGER_POSTURE_UNCERTAINTIES = StringListMetadataField("secrets_manager_posture_uncertainties")
    SECRETS_MANAGER_OPERATION_AUTHORIZATION_UNCERTAINTIES = StringListMetadataField(
        "secrets_manager_operation_authorization_uncertainties"
    )
    UNRESOLVED_FUNCTION_REFERENCES = StringListMetadataField("unresolved_function_references")
    CONTAINER_IMAGE_POSTURE_UNCERTAINTIES = StringListMetadataField("container_image_posture_uncertainties")
    ECS_SECRET_POSTURE_UNCERTAINTIES = StringListMetadataField("ecs_secret_posture_uncertainties")
    ECS_NETWORK_POSTURE_UNCERTAINTIES = StringListMetadataField("ecs_network_posture_uncertainties")
    ECS_SECURITY_GROUP_REFERENCE_STATE = OptionalStringMetadataField("ecs_security_group_reference_state")
    ECS_SYMBOLIC_SECURITY_GROUP_ADDRESSES = StringListMetadataField("ecs_symbolic_security_group_addresses")
    REQUIRES_COMPATIBILITIES = StringListMetadataField("requires_compatibilities")
    TRUST_PRINCIPALS = StringListMetadataField("trust_principals")
    RESOURCE_POLICY_SOURCE_ADDRESSES = StringListMetadataField("resource_policy_source_addresses")
    LOAD_BALANCER_TARGET_GROUP_ARNS = StringListMetadataField("target_group_arns")
    LOAD_BALANCER_ACTIONS = DictListMetadataField("load_balancer_actions")
    LOAD_BALANCER_CONDITIONS = DictListMetadataField("load_balancer_conditions")
    LOAD_BALANCER_CONDITION_UNCERTAINTIES = StringListMetadataField("load_balancer_condition_uncertainties")
    LOAD_BALANCER_RULE_PRIORITY = OptionalIntMetadataField("listener_rule_priority")
    ECS_FORWARDING_ASSOCIATIONS = DictListMetadataField("ecs_forwarding_associations")
    ECS_FORWARDING_UNCERTAINTIES = StringListMetadataField("ecs_forwarding_uncertainties")
    NETWORK_ATTACHMENTS = DictMetadataField("network_attachments")
    SECURITY_GROUP_TRAFFIC_RULES = DictListMetadataField("security_group_traffic_rules")
    SECURITY_GROUP_TRAFFIC_RULES_KNOWN = BoolMetadataField("security_group_traffic_rules_known")
    ECS_CONTAINER_NETWORK = DictMetadataField("ecs_container_network")
    ECS_PUBLIC_INGRESS_PATHS = DictListMetadataField("ecs_public_ingress_paths")
    ECS_PUBLIC_INGRESS_DECISIONS = DictListMetadataField("ecs_public_ingress_decisions")
    ECS_PUBLIC_INGRESS_UNCERTAINTIES = StringListMetadataField("ecs_public_ingress_uncertainties")
    LOAD_BALANCER_LISTENER_PORT = OptionalIntMetadataField("load_balancer_listener_port")
    LOAD_BALANCER_IP_ADDRESS_TYPE = OptionalStringMetadataField("load_balancer_ip_address_type")
    LOAD_BALANCER_TARGET_PROTOCOL = OptionalStringMetadataField("load_balancer_target_protocol")
    LOAD_BALANCER_TARGET_TYPE = OptionalStringMetadataField("load_balancer_target_type")
    LOAD_BALANCER_TARGET_IP_ADDRESS_TYPE = OptionalStringMetadataField("load_balancer_target_ip_address_type")

    SECURITY_GROUP_ID = OptionalStringMetadataField("security_group_id")
    ROLE_REFERENCE = OptionalStringMetadataField("role")
    IAM_INSTANCE_PROFILE = OptionalStringMetadataField("iam_instance_profile")
    POLICY_ARN = OptionalStringMetadataField("policy_arn")
    POLICY_NAME = OptionalStringMetadataField("policy_name")
    ACCOUNT_IDENTITY_SOURCE_MODE = OptionalStringMetadataField("account_identity_source_mode")
    ACCOUNT_IDENTITY_ARN_INPUTS = RecordListMetadataField[AwsAccountArnInput]("account_identity_arn_inputs")
    CALLER_IDENTITY_ACCOUNT_ID = OptionalStringMetadataField("caller_identity_account_id")
    CALLER_IDENTITY_ACCOUNT_ID_STATE = OptionalStringMetadataField("caller_identity_account_id_state")
    CALLER_IDENTITY_ACCOUNT_EVIDENCE = StringListMetadataField("caller_identity_account_evidence")
    CALLER_IDENTITY_USER_ID = OptionalStringMetadataField("caller_identity_user_id")
    OIDC_PROVIDER_URL = OptionalStringMetadataField("oidc_provider_url")
    OIDC_PROVIDER_ARN = OptionalStringMetadataField("oidc_provider_arn")
    CLUSTER_REFERENCE = OptionalStringMetadataField("cluster")
    NAME = OptionalStringMetadataField("name")
    CIDR_BLOCK = OptionalStringMetadataField("cidr_block")
    LOAD_BALANCER_TYPE = OptionalStringMetadataField("load_balancer_type")
    LOAD_BALANCER_ARN = OptionalStringMetadataField("load_balancer_arn")
    LISTENER_ARN = OptionalStringMetadataField("listener_arn")
    TASK_DEFINITION_REFERENCE = OptionalStringMetadataField("task_definition")
    TASK_DEFINITION_FAMILY = OptionalStringMetadataField("family")
    NETWORK_MODE = OptionalStringMetadataField("network_mode")
    TASK_ROLE_ARN = OptionalStringMetadataField("task_role_arn")
    EXECUTION_ROLE_ARN = OptionalStringMetadataField("execution_role_arn")
    SECRET_ARN = OptionalStringMetadataField("secret_arn")
    SECRETS_MANAGER_KMS_KEY_ID = OptionalStringMetadataField("secrets_manager_kms_key_id")
    SECRETS_MANAGER_ROTATION_SECRET_ID = OptionalStringMetadataField("secrets_manager_rotation_secret_id")
    SECRETS_MANAGER_ROTATION_SOURCE_ADDRESS = OptionalStringMetadataField("secrets_manager_rotation_source_address")
    SECRETS_MANAGER_ROTATION_LAMBDA_ARN = OptionalStringMetadataField("secrets_manager_rotation_lambda_arn")
    SECRETS_MANAGER_ROTATION_DURATION = OptionalStringMetadataField("secrets_manager_rotation_duration")
    SECRETS_MANAGER_ROTATION_SCHEDULE_EXPRESSION = OptionalStringMetadataField(
        "secrets_manager_rotation_schedule_expression"
    )
    FUNCTION_NAME = OptionalStringMetadataField("function_name")
    LAMBDA_PACKAGE_TYPE = OptionalStringMetadataField("lambda_package_type")
    ROUTE_TABLE_ID = OptionalStringMetadataField("route_table_id")
    SUBNET_ID = OptionalStringMetadataField("subnet_id")
    BUCKET_NAME = OptionalStringMetadataField("bucket")
    BUCKET_ACL = OptionalStringMetadataField("acl")
    S3_VERSIONING_STATUS = OptionalStringMetadataField("s3_versioning_status")
    S3_VERSIONING_SOURCE_ADDRESS = OptionalStringMetadataField("s3_versioning_source_address")
    S3_ENCRYPTION_ALGORITHM = OptionalStringMetadataField("s3_encryption_algorithm")
    S3_KMS_MASTER_KEY_ID = OptionalStringMetadataField("s3_kms_master_key_id")
    S3_BUCKET_KEY_ENABLED_STATE = OptionalStringMetadataField("s3_bucket_key_enabled_state")
    S3_ENCRYPTION_SOURCE_ADDRESS = OptionalStringMetadataField("s3_encryption_source_address")
    S3_OBJECT_LOCK_ENABLED_STATE = OptionalStringMetadataField("s3_object_lock_enabled_state")
    S3_OBJECT_LOCK_DEFAULT_RETENTION_MODE = OptionalStringMetadataField("s3_object_lock_default_retention_mode")
    S3_OBJECT_LOCK_SOURCE_ADDRESS = OptionalStringMetadataField("s3_object_lock_source_address")
    S3_LIFECYCLE_SOURCE_ADDRESS = OptionalStringMetadataField("s3_lifecycle_source_address")
    EKS_CLUSTER_ARN = OptionalStringMetadataField("eks_cluster_arn")
    EKS_CLUSTER_ROLE_ARN = OptionalStringMetadataField("eks_cluster_role_arn")
    EKS_KUBERNETES_VERSION = OptionalStringMetadataField("eks_kubernetes_version")
    EKS_ENDPOINT_PUBLIC_ACCESS_STATE = OptionalStringMetadataField("eks_endpoint_public_access_state")
    EKS_ENDPOINT_PRIVATE_ACCESS_STATE = OptionalStringMetadataField("eks_endpoint_private_access_state")
    EKS_PUBLIC_ACCESS_CIDRS_STATE = OptionalStringMetadataField("eks_public_access_cidrs_state")
    EKS_CLUSTER_SECURITY_GROUP_ID = OptionalStringMetadataField("eks_cluster_security_group_id")
    EKS_CONTROL_PLANE_LOGGING_STATE = OptionalStringMetadataField("eks_control_plane_logging_state")
    EKS_ENCRYPTION_CONFIG_STATE = OptionalStringMetadataField("eks_encryption_config_state")
    EKS_SECRETS_ENCRYPTION_STATE = OptionalStringMetadataField("eks_secrets_encryption_state")
    EKS_ENCRYPTION_KEY_ARN = OptionalStringMetadataField("eks_encryption_key_arn")
    EKS_AUTHENTICATION_MODE = OptionalStringMetadataField("eks_authentication_mode")
    EKS_BOOTSTRAP_CLUSTER_CREATOR_ADMIN_PERMISSIONS_STATE = OptionalStringMetadataField(
        "eks_bootstrap_cluster_creator_admin_permissions_state"
    )
    EKS_ACCESS_CONFIG_STATE = OptionalStringMetadataField("eks_access_config_state")
    EKS_ADDON_NAME = OptionalStringMetadataField("eks_addon_name")
    EKS_ADDON_CLUSTER_NAME = OptionalStringMetadataField("eks_addon_cluster_name")
    EKS_ADDON_VERSION = OptionalStringMetadataField("eks_addon_version")
    EKS_ADDON_CONFIGURATION_VALUES = OptionalStringMetadataField("eks_addon_configuration_values")
    EKS_ADDON_PRESERVE_STATE = OptionalStringMetadataField("eks_addon_preserve_state")
    EKS_ADDON_SERVICE_ACCOUNT_ROLE_ARN = OptionalStringMetadataField("eks_addon_service_account_role_arn")
    EKS_ADDON_TARGET_CLASS = OptionalStringMetadataField("eks_addon_target_class")
    VPC_ENDPOINT_ID = OptionalStringMetadataField("vpc_endpoint_id")
    VPC_ENDPOINT_SERVICE_NAME = OptionalStringMetadataField("vpc_endpoint_service_name")
    VPC_ENDPOINT_SERVICE_FAMILY = OptionalStringMetadataField("vpc_endpoint_service_family")
    VPC_ENDPOINT_TYPE = OptionalStringMetadataField("vpc_endpoint_type")
    VPC_ENDPOINT_VPC_ID = OptionalStringMetadataField("vpc_endpoint_vpc_id")
    VPC_ENDPOINT_PRIVATE_DNS_ENABLED_STATE = OptionalStringMetadataField("vpc_endpoint_private_dns_enabled_state")
    FLOW_LOG_ID = OptionalStringMetadataField("flow_log_id")
    FLOW_LOG_TARGET_TYPE = OptionalStringMetadataField("flow_log_target_type")
    FLOW_LOG_TARGET_ID = OptionalStringMetadataField("flow_log_target_id")
    FLOW_LOG_TRAFFIC_TYPE = OptionalStringMetadataField("flow_log_traffic_type")
    FLOW_LOG_DESTINATION_TYPE = OptionalStringMetadataField("flow_log_destination_type")
    FLOW_LOG_DESTINATION = OptionalStringMetadataField("flow_log_destination")
    FLOW_LOG_LOG_GROUP_NAME = OptionalStringMetadataField("flow_log_log_group_name")
    FLOW_LOG_IAM_ROLE_ARN = OptionalStringMetadataField("flow_log_iam_role_arn")
    LAMBDA_FUNCTION_URL = OptionalStringMetadataField("lambda_function_url")
    LAMBDA_FUNCTION_URL_AUTHORIZATION_TYPE = OptionalStringMetadataField("lambda_function_url_authorization_type")
    LAMBDA_FUNCTION_URL_QUALIFIER = OptionalStringMetadataField("lambda_function_url_qualifier")
    LAMBDA_FUNCTION_URL_INVOKE_MODE = OptionalStringMetadataField("lambda_function_url_invoke_mode")
    LAMBDA_FUNCTION_URL_CORS_ALLOW_CREDENTIALS_STATE = OptionalStringMetadataField(
        "lambda_function_url_cors_allow_credentials_state"
    )
    API_GATEWAY_API_ID = OptionalStringMetadataField("api_gateway_api_id")
    API_GATEWAY_NAME = OptionalStringMetadataField("api_gateway_name")
    API_GATEWAY_DESCRIPTION = OptionalStringMetadataField("api_gateway_description")
    API_GATEWAY_PROTOCOL_TYPE = OptionalStringMetadataField("api_gateway_protocol_type")
    API_GATEWAY_API_ENDPOINT = OptionalStringMetadataField("api_gateway_api_endpoint")
    API_GATEWAY_EXECUTION_ARN = OptionalStringMetadataField("api_gateway_execution_arn")
    API_GATEWAY_EXECUTE_API_ENDPOINT_STATE = OptionalStringMetadataField("api_gateway_execute_api_endpoint_state")
    API_GATEWAY_PUBLIC_ENDPOINT_STATE = OptionalStringMetadataField("api_gateway_public_endpoint_state")
    API_GATEWAY_ROUTE_SELECTION_EXPRESSION = OptionalStringMetadataField("api_gateway_route_selection_expression")
    API_GATEWAY_ROUTE_KEY = OptionalStringMetadataField("api_gateway_route_key")
    API_GATEWAY_OPENAPI_BODY_STATE = OptionalStringMetadataField("api_gateway_openapi_body_state")
    API_GATEWAY_PARENT_API_ADDRESS = OptionalStringMetadataField("api_gateway_parent_api_address")
    API_GATEWAY_METHOD_RESOURCE_ID = OptionalStringMetadataField("api_gateway_method_resource_id")
    API_GATEWAY_METHOD_HTTP_METHOD = OptionalStringMetadataField("api_gateway_method_http_method")
    API_GATEWAY_AUTHORIZATION_TYPE = OptionalStringMetadataField("api_gateway_authorization_type")
    API_GATEWAY_AUTHORIZER_ID = OptionalStringMetadataField("api_gateway_authorizer_id")
    API_GATEWAY_STAGE_NAME = OptionalStringMetadataField("api_gateway_stage_name")
    API_GATEWAY_ACCESS_LOG_DESTINATION_ARN = OptionalStringMetadataField("api_gateway_access_log_destination_arn")
    API_GATEWAY_ACCESS_LOG_FORMAT = OptionalStringMetadataField("api_gateway_access_log_format")
    API_GATEWAY_AUTHORIZER_NAME = OptionalStringMetadataField("api_gateway_authorizer_name")
    API_GATEWAY_AUTHORIZER_TYPE = OptionalStringMetadataField("api_gateway_authorizer_type")
    API_GATEWAY_AUTHORIZER_URI = OptionalStringMetadataField("api_gateway_authorizer_uri")
    API_GATEWAY_AUTHORIZER_CREDENTIALS = OptionalStringMetadataField("api_gateway_authorizer_credentials")
    API_GATEWAY_IDENTITY_SOURCE = OptionalStringMetadataField("api_gateway_identity_source")
    API_GATEWAY_IDENTITY_VALIDATION_EXPRESSION = OptionalStringMetadataField(
        "api_gateway_identity_validation_expression"
    )
    LOAD_BALANCER_LISTENER_PROTOCOL = OptionalStringMetadataField("load_balancer_listener_protocol")
    LOAD_BALANCER_LISTENER_CERTIFICATE_ARN = OptionalStringMetadataField("load_balancer_listener_certificate_arn")
    LOAD_BALANCER_LISTENER_SSL_POLICY = OptionalStringMetadataField("load_balancer_listener_ssl_policy")
    CLOUDFRONT_DISTRIBUTION_ID = OptionalStringMetadataField("cloudfront_distribution_id")
    CLOUDFRONT_DISTRIBUTION_ARN = OptionalStringMetadataField("cloudfront_distribution_arn")
    CLOUDFRONT_DOMAIN_NAME = OptionalStringMetadataField("cloudfront_domain_name")
    CLOUDFRONT_ENABLED_STATE = OptionalStringMetadataField("cloudfront_enabled_state")
    CLOUDFRONT_IPV6_ENABLED_STATE = OptionalStringMetadataField("cloudfront_ipv6_enabled_state")
    CLOUDFRONT_HTTP_VERSION = OptionalStringMetadataField("cloudfront_http_version")
    CLOUDFRONT_DEFAULT_ROOT_OBJECT = OptionalStringMetadataField("cloudfront_default_root_object")
    CLOUDFRONT_WEB_ACL_ID = OptionalStringMetadataField("cloudfront_web_acl_id")
    CLOUDFRONT_DEFAULT_VIEWER_PROTOCOL_POLICY = OptionalStringMetadataField("cloudfront_default_viewer_protocol_policy")
    CLOUDFRONT_VIEWER_CERTIFICATE_SOURCE = OptionalStringMetadataField("cloudfront_viewer_certificate_source")
    CLOUDFRONT_DEFAULT_CERTIFICATE_STATE = OptionalStringMetadataField("cloudfront_default_certificate_state")
    CLOUDFRONT_MINIMUM_PROTOCOL_VERSION = OptionalStringMetadataField("cloudfront_minimum_protocol_version")
    CLOUDFRONT_SSL_SUPPORT_METHOD = OptionalStringMetadataField("cloudfront_ssl_support_method")
    CLOUDFRONT_ACM_CERTIFICATE_ARN = OptionalStringMetadataField("cloudfront_acm_certificate_arn")
    CLOUDFRONT_IAM_CERTIFICATE_ID = OptionalStringMetadataField("cloudfront_iam_certificate_id")
    CLOUDFRONT_LOGGING_STATE = OptionalStringMetadataField("cloudfront_logging_state")
    CLOUDFRONT_LOGGING_BUCKET = OptionalStringMetadataField("cloudfront_logging_bucket")
    CLOUDFRONT_LOGGING_PREFIX = OptionalStringMetadataField("cloudfront_logging_prefix")
    WEB_ACL_ID = OptionalStringMetadataField("web_acl_id")
    WEB_ACL_NAME = OptionalStringMetadataField("web_acl_name")
    WEB_ACL_ARN = OptionalStringMetadataField("web_acl_arn")
    WEB_ACL_SCOPE = OptionalStringMetadataField("web_acl_scope")
    WEB_ACL_DEFAULT_ACTION = OptionalStringMetadataField("web_acl_default_action")
    WEB_ACL_ASSOCIATION_RESOURCE_ARN = OptionalStringMetadataField("web_acl_association_resource_arn")
    WEB_ACL_ASSOCIATION_WEB_ACL_ARN = OptionalStringMetadataField("web_acl_association_web_acl_arn")
    CLOUDTRAIL_S3_BUCKET_NAME = OptionalStringMetadataField("cloudtrail_s3_bucket_name")
    CLOUDTRAIL_S3_KEY_PREFIX = OptionalStringMetadataField("cloudtrail_s3_key_prefix")
    CLOUDTRAIL_KMS_KEY_ID = OptionalStringMetadataField("cloudtrail_kms_key_id")
    CLOUDTRAIL_CLOUDWATCH_LOGS_GROUP_ARN = OptionalStringMetadataField("cloudtrail_cloudwatch_logs_group_arn")
    CLOUDTRAIL_CLOUDWATCH_LOGS_ROLE_ARN = OptionalStringMetadataField("cloudtrail_cloudwatch_logs_role_arn")
    CLOUDTRAIL_ENABLE_LOGGING_STATE = OptionalStringMetadataField("cloudtrail_enable_logging_state")
    CLOUDTRAIL_LOG_FILE_VALIDATION_STATE = OptionalStringMetadataField("cloudtrail_log_file_validation_state")
    CLOUDTRAIL_MULTI_REGION_STATE = OptionalStringMetadataField("cloudtrail_multi_region_state")
    CLOUDTRAIL_GLOBAL_SERVICE_EVENTS_STATE = OptionalStringMetadataField("cloudtrail_global_service_events_state")
    CLOUDTRAIL_ORGANIZATION_TRAIL_STATE = OptionalStringMetadataField("cloudtrail_organization_trail_state")
    GUARDDUTY_ENABLE_STATE = OptionalStringMetadataField("guardduty_enable_state")
    GUARDDUTY_FINDING_PUBLISHING_FREQUENCY = OptionalStringMetadataField("guardduty_finding_publishing_frequency")
    SECURITYHUB_ENABLE_DEFAULT_STANDARDS_STATE = OptionalStringMetadataField(
        "securityhub_enable_default_standards_state"
    )
    SECURITYHUB_AUTO_ENABLE_CONTROLS_STATE = OptionalStringMetadataField("securityhub_auto_enable_controls_state")
    SECURITYHUB_CONTROL_FINDING_GENERATOR = OptionalStringMetadataField("securityhub_control_finding_generator")
    CONFIG_RECORDER_NAME = OptionalStringMetadataField("config_recorder_name")
    CONFIG_RECORDER_ROLE_ARN = OptionalStringMetadataField("config_recorder_role_arn")
    CONFIG_RECORDER_ALL_SUPPORTED_STATE = OptionalStringMetadataField("config_recorder_all_supported_state")
    CONFIG_RECORDER_INCLUDE_GLOBAL_RESOURCE_TYPES_STATE = OptionalStringMetadataField(
        "config_recorder_include_global_resource_types_state"
    )
    CONFIG_RECORDER_RECORDING_STRATEGY_USE_ONLY = OptionalStringMetadataField(
        "config_recorder_recording_strategy_use_only"
    )
    CONFIG_RECORDER_STATUS_NAME = OptionalStringMetadataField("config_recorder_status_name")
    CONFIG_RECORDER_IS_ENABLED_STATE = OptionalStringMetadataField("config_recorder_is_enabled_state")
    CONFIG_DELIVERY_CHANNEL_NAME = OptionalStringMetadataField("config_delivery_channel_name")
    CONFIG_DELIVERY_CHANNEL_S3_BUCKET_NAME = OptionalStringMetadataField("config_delivery_channel_s3_bucket_name")
    CONFIG_DELIVERY_CHANNEL_S3_KEY_PREFIX = OptionalStringMetadataField("config_delivery_channel_s3_key_prefix")
    CONFIG_DELIVERY_CHANNEL_SNS_TOPIC_ARN = OptionalStringMetadataField("config_delivery_channel_sns_topic_arn")
    ACCESS_ANALYZER_NAME = OptionalStringMetadataField("access_analyzer_name")
    ACCESS_ANALYZER_TYPE = OptionalStringMetadataField("access_analyzer_type")
    ACCESS_ANALYZER_STATUS = OptionalStringMetadataField("access_analyzer_status")
    ACCESS_ANALYZER_ARN = OptionalStringMetadataField("access_analyzer_arn")
    MACIE_ACCOUNT_STATUS = OptionalStringMetadataField("macie_account_status")
    MACIE_ACCOUNT_STATUS_STATE = OptionalStringMetadataField("macie_account_status_state")
    MACIE_FINDING_PUBLISHING_FREQUENCY = OptionalStringMetadataField("macie_finding_publishing_frequency")
    SNS_DISPLAY_NAME = OptionalStringMetadataField("sns_display_name")
    SNS_KMS_MASTER_KEY_ID = OptionalStringMetadataField("sns_kms_master_key_id")
    SNS_ENCRYPTION_OWNERSHIP_STATE = OptionalStringMetadataField("sns_encryption_ownership_state")
    SNS_TOPIC_POLICY_STATE = OptionalStringMetadataField("sns_topic_policy_state")
    SQS_QUEUE_URL = OptionalStringMetadataField("sqs_queue_url")
    SQS_KMS_MASTER_KEY_ID = OptionalStringMetadataField("sqs_kms_master_key_id")
    SQS_MANAGED_SSE_ENABLED_STATE = OptionalStringMetadataField("sqs_managed_sse_enabled_state")
    SQS_ENCRYPTION_OWNERSHIP_STATE = OptionalStringMetadataField("sqs_encryption_ownership_state")
    SQS_REDRIVE_STATE = OptionalStringMetadataField("sqs_redrive_state")
    SQS_REDRIVE_TARGET_ARN = OptionalStringMetadataField("sqs_redrive_target_arn")
    SQS_QUEUE_POLICY_STATE = OptionalStringMetadataField("sqs_queue_policy_state")
    SQS_REDRIVE_SOURCE_ADDRESS = OptionalStringMetadataField("sqs_redrive_source_address")
    ECR_REPOSITORY_URL = OptionalStringMetadataField("ecr_repository_url")
    ECR_ENCRYPTION_TYPE = OptionalStringMetadataField("ecr_encryption_type")
    ECR_KMS_KEY = OptionalStringMetadataField("ecr_kms_key")
    ECR_ENCRYPTION_OWNERSHIP_STATE = OptionalStringMetadataField("ecr_encryption_ownership_state")
    ECR_IMAGE_TAG_MUTABILITY = OptionalStringMetadataField("ecr_image_tag_mutability")
    ECR_REPOSITORY_SCAN_ON_PUSH_STATE = OptionalStringMetadataField("ecr_repository_scan_on_push_state")
    ECR_REGISTRY_SCAN_TYPE = OptionalStringMetadataField("ecr_registry_scan_type")
    ECR_REGISTRY_SCANNING_COVERAGE_STATE = OptionalStringMetadataField("ecr_registry_scanning_coverage_state")
    RDS_PUBLICLY_ACCESSIBLE_STATE = OptionalStringMetadataField("rds_publicly_accessible_state")
    RDS_DELETION_PROTECTION_STATE = OptionalStringMetadataField("rds_deletion_protection_state")
    RDS_MULTI_AZ_STATE = OptionalStringMetadataField("rds_multi_az_state")
    RDS_KMS_KEY_ID = OptionalStringMetadataField("rds_kms_key_id")
    RDS_PERFORMANCE_INSIGHTS_ENABLED_STATE = OptionalStringMetadataField("rds_performance_insights_enabled_state")
    RDS_IAM_DATABASE_AUTHENTICATION_ENABLED_STATE = OptionalStringMetadataField(
        "rds_iam_database_authentication_enabled_state"
    )
    DYNAMODB_TABLE_ARN = OptionalStringMetadataField("dynamodb_table_arn")
    DYNAMODB_KMS_KEY_ARN = OptionalStringMetadataField("dynamodb_kms_key_arn")
    DYNAMODB_ENCRYPTION_OWNERSHIP_STATE = OptionalStringMetadataField("dynamodb_encryption_ownership_state")
    DYNAMODB_ENCRYPTION_CONFIGURATION_STATE = OptionalStringMetadataField("dynamodb_encryption_configuration_state")
    DYNAMODB_PITR_STATE = OptionalStringMetadataField("dynamodb_pitr_state")
    DYNAMODB_DELETION_PROTECTION_STATE = OptionalStringMetadataField("dynamodb_deletion_protection_state")
    DYNAMODB_RESOURCE_POLICY_TARGET_REFERENCE = OptionalStringMetadataField("dynamodb_resource_policy_target_reference")
    KMS_KEY_ID = OptionalStringMetadataField("kms_key_id")
    KMS_KEY_ARN = OptionalStringMetadataField("kms_key_arn")
    KMS_KEY_USAGE = OptionalStringMetadataField("kms_key_usage")
    KMS_KEY_SPEC = OptionalStringMetadataField("kms_key_spec")
    KMS_CUSTOMER_MASTER_KEY_SPEC = OptionalStringMetadataField("kms_customer_master_key_spec")
    KMS_KEY_ORIGIN = OptionalStringMetadataField("kms_key_origin")
    KMS_MULTI_REGION_STATE = OptionalStringMetadataField("kms_multi_region_state")
    KMS_CUSTOM_KEY_STORE_ID = OptionalStringMetadataField("kms_custom_key_store_id")
    KMS_XKS_KEY_ID = OptionalStringMetadataField("kms_xks_key_id")
    KMS_ENABLE_KEY_ROTATION_STATE = OptionalStringMetadataField("kms_enable_key_rotation_state")
    KMS_POLICY_CONFIGURATION_STATE = OptionalStringMetadataField("kms_policy_configuration_state")
    KMS_POLICY_COMPLETENESS_STATE = OptionalStringMetadataField("kms_policy_completeness_state")
    KMS_POLICY_SOURCE_ADDRESSES = StringListMetadataField("kms_policy_source_addresses")
    KMS_POLICY_POSTURE_UNCERTAINTIES = StringListMetadataField("kms_policy_posture_uncertainties")
    KMS_ENCRYPTION_DEPENDENCIES = RecordListMetadataField[AwsKmsEncryptionDependency]("kms_encryption_dependencies")
    KMS_ENCRYPTION_DEPENDENCY_UNCERTAINTIES = StringListMetadataField("kms_encryption_dependency_uncertainties")
    KMS_ALIASES = RecordListMetadataField[AwsKmsAliasRelationship]("kms_aliases")
    KMS_GRANTS = RecordListMetadataField[AwsKmsGrantRelationship]("kms_grants")
    KMS_KEY_POLICIES = RecordListMetadataField[AwsKmsKeyPolicyEvidence]("kms_key_policies")
    KMS_OPERATION_AUTHORIZATIONS = RecordListMetadataField[AwsKmsOperationAuthorization]("kms_operation_authorizations")
    KMS_OPERATION_AUTHORIZATION_UNCERTAINTIES = StringListMetadataField("kms_operation_authorization_uncertainties")
    KMS_UNRESOLVED_KEY_REFERENCES = StringListMetadataField("kms_unresolved_key_references")
    KMS_ALIAS_NAME = OptionalStringMetadataField("kms_alias_name")
    KMS_ALIAS_NAME_PREFIX = OptionalStringMetadataField("kms_alias_name_prefix")
    KMS_ALIAS_ARN = OptionalStringMetadataField("kms_alias_arn")
    KMS_ALIAS_TARGET_KEY_ID = OptionalStringMetadataField("kms_alias_target_key_id")
    KMS_ALIAS_TARGET_KEY_ARN = OptionalStringMetadataField("kms_alias_target_key_arn")
    KMS_ALIAS_TARGET_KEY_REFERENCE = OptionalStringMetadataField("kms_alias_target_key_reference")
    KMS_ALIAS_RESOLVED_KEY_ADDRESS = OptionalStringMetadataField("kms_alias_resolved_key_address")
    KMS_ALIAS_POSTURE_UNCERTAINTIES = StringListMetadataField("kms_alias_posture_uncertainties")
    KMS_GRANT_ID = OptionalStringMetadataField("kms_grant_id")
    KMS_GRANT_NAME = OptionalStringMetadataField("kms_grant_name")
    KMS_GRANT_KEY_REFERENCE = OptionalStringMetadataField("kms_grant_key_reference")
    KMS_GRANT_GRANTEE_PRINCIPAL = OptionalStringMetadataField("kms_grant_grantee_principal")
    KMS_GRANT_OPERATIONS = StringListMetadataField("kms_grant_operations")
    KMS_GRANT_RETIRING_PRINCIPAL = OptionalStringMetadataField("kms_grant_retiring_principal")
    KMS_GRANT_CONSTRAINTS = DictMetadataField("kms_grant_constraints")
    KMS_GRANT_RETIRE_ON_DELETE_STATE = OptionalStringMetadataField("kms_grant_retire_on_delete_state")
    KMS_GRANT_RESOLVED_KEY_ADDRESS = OptionalStringMetadataField("kms_grant_resolved_key_address")
    KMS_GRANT_POSTURE_UNCERTAINTIES = StringListMetadataField("kms_grant_posture_uncertainties")
    KMS_KEY_POLICY_KEY_REFERENCE = OptionalStringMetadataField("kms_key_policy_key_reference")
    KMS_KEY_POLICY_RESOLVED_KEY_ADDRESS = OptionalStringMetadataField("kms_key_policy_resolved_key_address")
    KMS_KEY_POLICY_BYPASS_LOCKOUT_SAFETY_CHECK_STATE = OptionalStringMetadataField(
        "kms_key_policy_bypass_lockout_safety_check_state"
    )
    KMS_KEY_POLICY_POSTURE_UNCERTAINTIES = StringListMetadataField("kms_key_policy_posture_uncertainties")
    ENGINE = OptionalStringMetadataField("engine")

    SQS_MESSAGE_RETENTION_SECONDS = OptionalIntMetadataField("sqs_message_retention_seconds")
    SQS_REDRIVE_MAX_RECEIVE_COUNT = OptionalIntMetadataField("sqs_redrive_max_receive_count")
    RDS_BACKUP_RETENTION_PERIOD = OptionalIntMetadataField("rds_backup_retention_period")
    DYNAMODB_PITR_RECOVERY_PERIOD_DAYS = OptionalIntMetadataField("dynamodb_pitr_recovery_period_days")
    KMS_DELETION_WINDOW_IN_DAYS = OptionalIntMetadataField("kms_deletion_window_in_days")
    KMS_ROTATION_PERIOD_IN_DAYS = OptionalIntMetadataField("kms_rotation_period_in_days")
    S3_OBJECT_LOCK_DEFAULT_RETENTION_DAYS = OptionalIntMetadataField("s3_object_lock_default_retention_days")
    S3_OBJECT_LOCK_DEFAULT_RETENTION_YEARS = OptionalIntMetadataField("s3_object_lock_default_retention_years")
    S3_LIFECYCLE_RULE_COUNT = OptionalIntMetadataField("s3_lifecycle_rule_count")
    FLOW_LOG_MAX_AGGREGATION_INTERVAL = OptionalIntMetadataField("flow_log_max_aggregation_interval")
    SECRETS_MANAGER_RECOVERY_WINDOW_IN_DAYS = OptionalIntMetadataField("secrets_manager_recovery_window_in_days")
    SECRETS_MANAGER_ROTATION_AUTOMATICALLY_AFTER_DAYS = OptionalIntMetadataField(
        "secrets_manager_rotation_automatically_after_days"
    )
    LAMBDA_FUNCTION_URL_CORS_MAX_AGE = OptionalIntMetadataField("lambda_function_url_cors_max_age")
    API_GATEWAY_AUTHORIZER_RESULT_TTL = OptionalIntMetadataField("api_gateway_authorizer_result_ttl")
    TASK_DEFINITION_REVISION = OptionalIntMetadataField("revision")

    POLICY_DOCUMENT = DictMetadataField("policy_document")
    SQS_REDRIVE_POLICY = DictMetadataField("sqs_redrive_policy")
    S3_VERSIONING_CONFIGURATION = DictMetadataField("s3_versioning_configuration")
    S3_SERVER_SIDE_ENCRYPTION_CONFIGURATION = DictMetadataField("s3_server_side_encryption_configuration")
    S3_OBJECT_LOCK_CONFIGURATION = DictMetadataField("s3_object_lock_configuration")
    EKS_VPC_CONFIG = DictMetadataField("eks_vpc_config")
    EKS_ACCESS_CONFIG = DictMetadataField("eks_access_config")
    VPC_ENDPOINT_POLICY_DOCUMENT = DictMetadataField("vpc_endpoint_policy_document")
    FLOW_LOG_DESTINATION_OPTIONS = DictMetadataField("flow_log_destination_options")
    WEB_ACL_DEFAULT_ACTION_EVIDENCE = DictMetadataField("web_acl_default_action_evidence")
    GUARDDUTY_DATASOURCES = DictMetadataField("guardduty_datasources")
    CONFIG_RECORDER_RECORDING_GROUP = DictMetadataField("config_recorder_recording_group")
    CONFIG_RECORDER_RECORDING_STRATEGY = DictMetadataField("config_recorder_recording_strategy")
    ACCESS_ANALYZER_CONFIGURATION = DictMetadataField("access_analyzer_configuration")
    LAMBDA_FUNCTION_URL_CORS = DictMetadataField("lambda_function_url_cors")
    API_GATEWAY_ENDPOINT_CONFIGURATION = DictMetadataField("api_gateway_endpoint_configuration")
    API_GATEWAY_CORS_CONFIGURATION = DictMetadataField("api_gateway_cors_configuration")
    CLOUDFRONT_VIEWER_CERTIFICATE = DictMetadataField("cloudfront_viewer_certificate")
    CLOUDFRONT_DEFAULT_CACHE_BEHAVIOR = DictMetadataField("cloudfront_default_cache_behavior")
    CLOUDFRONT_LOGGING_CONFIG = DictMetadataField("cloudfront_logging_config")
    ROUTES = DictListMetadataField("routes")
    TRUST_STATEMENTS = DictListMetadataField("trust_statements")
    ECS_LOAD_BALANCERS = DictListMetadataField("load_balancers")
    CONTAINER_IMAGE_REFERENCES = DictListMetadataField("container_image_references")
    ECS_SECRET_REFERENCES = DictListMetadataField("ecs_secret_references")
    ECS_SECRET_ACCESS_PATHS = DictListMetadataField("ecs_secret_access_paths")
    ECS_SECRET_MANAGEMENT_PATHS = RecordListMetadataField[AwsEcsSecretsManagerManagementPath](
        "ecs_secret_management_paths"
    )
    ECS_S3_ACCESS_PATHS = RecordListMetadataField[AwsEcsS3AccessPath]("ecs_s3_access_paths")
    ECS_S3_OBJECT_DELETION_PATHS = RecordListMetadataField[AwsEcsS3ObjectDeletionPath]("ecs_s3_object_deletion_paths")
    ECS_S3_BUCKET_TOPOLOGY_DESTRUCTION_PATHS = RecordListMetadataField[AwsEcsS3BucketTopologyDestructionPath](
        "ecs_s3_bucket_topology_destruction_paths"
    )
    ECS_S3_PROTECTED_DATA_CONVERGENCES = RecordListMetadataField[AwsEcsS3ProtectedDataConvergence](
        "ecs_s3_protected_data_convergences"
    )
    ECS_MESSAGING_ACCESS_PATHS = DictListMetadataField("ecs_messaging_access_paths")
    ECS_SQS_MESSAGE_REMOVAL_PATHS = RecordListMetadataField[AwsEcsSqsMessageRemovalPath](
        "ecs_sqs_message_removal_paths"
    )
    ECS_MESSAGING_TOPOLOGY_DESTRUCTION_PATHS = RecordListMetadataField[AwsEcsMessagingTopologyDestructionPath](
        "ecs_messaging_topology_destruction_paths"
    )
    ECS_DYNAMODB_ACCESS_PATHS = DictListMetadataField("ecs_dynamodb_access_paths")
    ECS_DYNAMODB_ITEM_DELETION_PATHS = RecordListMetadataField[AwsEcsDynamoDbItemDeletionPath](
        "ecs_dynamodb_item_deletion_paths"
    )
    ECS_DYNAMODB_TABLE_TOPOLOGY_DESTRUCTION_PATHS = RecordListMetadataField[AwsEcsDynamoDbTableTopologyDestructionPath](
        "ecs_dynamodb_table_topology_destruction_paths"
    )
    ECS_CLOUDTRAIL_AUDIT_TELEMETRY_DISRUPTION_PATHS = RecordListMetadataField[
        AwsEcsCloudTrailAuditTelemetryDisruptionPath
    ]("ecs_cloudtrail_audit_telemetry_disruption_paths")
    ECS_KMS_OPERATION_PATHS = RecordListMetadataField[AwsEcsKmsOperationPath]("ecs_kms_operation_paths")
    ECS_KMS_MANAGEMENT_PATHS = RecordListMetadataField[AwsEcsKmsManagementPath]("ecs_kms_management_paths")
    ECS_DYNAMODB_INDEX_RELATIONSHIPS = DictListMetadataField("ecs_dynamodb_index_relationships")
    ECR_WRITE_PATHS = DictListMetadataField("ecr_write_paths")
    S3_LIFECYCLE_RULES = DictListMetadataField("s3_lifecycle_rules")
    ECR_IMAGE_TAG_MUTABILITY_EXCLUSION_FILTERS = DictListMetadataField("ecr_image_tag_mutability_exclusion_filters")
    ECR_REGISTRY_SCANNING_RULES = DictListMetadataField("ecr_registry_scanning_rules")
    EKS_ENCRYPTION_CONFIG = DictListMetadataField("eks_encryption_config")
    DYNAMODB_REPLICAS = DictListMetadataField("dynamodb_replicas")
    VPC_ENDPOINT_DNS_ENTRIES = DictListMetadataField("vpc_endpoint_dns_entries")
    WEB_ACL_RULES = DictListMetadataField("web_acl_rules")
    CLOUDFRONT_ORIGINS = DictListMetadataField("cloudfront_origins")
    CLOUDFRONT_ORDERED_CACHE_BEHAVIORS = DictListMetadataField("cloudfront_ordered_cache_behaviors")
    CLOUDTRAIL_EVENT_SELECTORS = DictListMetadataField("cloudtrail_event_selectors")
    PRIVILEGED_ACCESS_GRANTS = DictListMetadataField("privileged_access_grants")
    GUARDDUTY_FEATURES = DictListMetadataField("guardduty_features")
    SECRETS_MANAGER_ROTATION_RULES = DictMetadataField("secrets_manager_rotation_rules")
    SECRETS_MANAGER_REPLICATION = DictListMetadataField("secrets_manager_replication")
    SECRETS_MANAGER_OPERATION_AUTHORIZATIONS = RecordListMetadataField[AwsSecretsManagerOperationAuthorization](
        "secrets_manager_operation_authorizations"
    )
    API_GATEWAY_METHODS = DictListMetadataField("api_gateway_methods")
    API_GATEWAY_STAGES = DictListMetadataField("api_gateway_stages")
    API_GATEWAY_AUTHORIZERS = DictListMetadataField("api_gateway_authorizers")
    API_GATEWAY_ROUTES = DictListMetadataField("api_gateway_routes")
    PUBLIC_ACCESS_BLOCK = BoolDictMetadataField("public_access_block")

    PUBLIC_ACCESS_CONFIGURED = ResourceMetadata.PUBLIC_ACCESS_CONFIGURED
    PUBLIC_ACCESS_REASONS = ResourceMetadata.PUBLIC_ACCESS_REASONS
    PUBLIC_EXPOSURE_REASONS = ResourceMetadata.PUBLIC_EXPOSURE_REASONS
